import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * 歌曲 YouTube 影片 IDs 對照表
 * 
 * 請在此處填入各歌曲的 YouTube IDs (多個 ID 請用英文逗號 "," 分隔)
 * 例如：
 *   "THE IDOLM@STER": "dQw4w9WgXcQ,abcdefg123",
 *   "Never say never": "xxxxxxxxx",
 */
const youtubeIdsMap: Record<string, string> = {
  "\"HELLO!\"": "zxBftixd3Gk,M6DyhuxoNw8",
  "“NOTHING TO LOSE\"": "Cf_QPbou4Ik",
  "#HE4DSHOT": "614X06BVSGQ,oyiwplYcQAw",
  "-LEGNE- 仇なす剣 光の旋律": "cFR2q8uRVCY",
  "...In The Name Of。 ...LOVE?": "qMwbifmv9ME,CIzjo9bCS3A,gUUV4XqQMA4",
  "...In The Name Of。 ...LOVE? (TeddyLoid Remix)": "CIzjo9bCS3A",
  "1,2,3": "-NVgekn55B4",
  "1/3": "2mn2ADwNFdc,UpCoEt3t0LA",
  "1/6の夢旅人": "",
  "100てん☆ナンバーワン！": "YqY5xwTRinA",
  "14平米にスーベニア": "hV6M0p7IBKQ,WAFd2J5gXeM",
  "14平米にスーベニア -広川恵一 Remix-": "nOmux8ZVFqE",
  "17才": "",
  "1st Call": "kpUUzqYAF8s,zhm1vC5aGz4",
  "283体操": "",
  "2nd SIDE": "aLyYSBS2G2E",
  "2nd SIDE -雨あがり Remix-": "",
  "315 Steelo!": "XFQ859tjOqY",
  "365日のストーリー": "kIQJgUHJZvA",
  "36℃ U･B･U": "szxn42peP3M,otlq2Ngwukk,cMHUxNhw_3s",
  "7 colors": "",
  "7Days A Week!!": "lgADirpZ7nU,rMBWH_pRJyQ",
  "99 Nights": "mQQgfsJt1a4,Trr3GjT4L7I,lIxGZ-QZ1nQ,htEh303DAGM",
  "9：02pm": "jfpQiFVPzEI",
  "A CUP OF HAPPINESS": "xjKIYU4Orgk",
  "ABSOLUTE RUN!!!": "MNmrqIOgaDI,Ligr-FCc-z4,85GmA8ZHif4",
  "ACE": "xrtoaQjxoNE,MvKjnIvBgIE,st2_yqx3iks",
  "AFTER THE RAIN": "fSjvzBJWaSQ",
  "AIKANE?": "X04Nj1Vyqqc,TSwrzHZypEs,s4YsJ6mlj1o",
  "ALIVE": "",
  "ALL nOR NOTHING": "gcVkYkXr9h0",
  "ALOHA! HAPPY CREATOR!": "2xz52BhT5Ug",
  "ALRIGHT*": "kJSeM-WFarE,f79HgflJQJs",
  "ANYWHERE": "1GARLNzOYBM",
  "ARRIVE TO STAR": "n0wkFUUk08s",
  "ART NEEDS HEART BEATS": "HPloOnGAyP0,P5y-jUOUJuU",
  "ASTERISK": "Ugp5BaWfMpg",
  "AVALON": "",
  "AZUR": "Vm2VaIvJlTk",
  "Absolute NIne": "6n9oklEdKWg",
  "Advance": "CKDsdaUn9qI",
  "After Run": "H24aRhIZoqo,GBy9OCb3z_Q",
  "Agape": "",
  "Alchemy": "lba8ajCKLvs",
  "Alice or Guilty": "",
  "All Alone": "",
  "Amber Color Oasis": "Krkx8SHzyyc",
  "Ambitious Eve": "NAa_ryW2RZ8",
  "AnemoneStar": "kum7HR4dRxo",
  "Angel Breeze": "HuTtCY-i2Qc",
  "Angelic Parade♪": "A9cr1ILM5oY,K4KYP9L8EbQ,wDTzOxC0lOM",
  "Anniversary": "XCBGCg_FTMQ",
  "Another Rampage": "Q3uzDZ_Gcsg",
  "Around Find World!": "gJwbHXAphZM",
  "Arrive You ～それが運命でも～": "krC-3nWC_Ws,frvzl-oywWA,_4qETshDPbg",
  "Arrowhead": "LTceGpfobjo",
  "Athanasia": "3xRnYZiVwEI",
  "Atmosphere": "R9PEnLmv6zI,uKG6NrHbEQ8",
  "Attacca Scenery": "6VnMnOYeZFc",
  "Avenue Illusion!": "NCwjzSvEoJY",
  "BACK FLIP☆EMOTION": "Gmba4y-oOr4",
  "BANG×BANG": "",
  "BEAST MODE": "ueadCLiVYEI",
  "BEST ROAD": "",
  "BEYOND THE STARLIGHT": "jfKf8tMAxA8,eDzsLG4EZM8,6GUp-bYbdKY",
  "BEYOND THE STARLIGHT -広川恵一 Remix-": "6GUp-bYbdKY",
  "BORN ON DREAM! ～HANABI☆NIGHT～": "r9yPbaiFUg4,QVDCXAdS_O8,UJ1bsJKXMyI",
  "BOUNCING♪ SMILE!": "4sLxH65WkAk,Tlzw2SGS1qo",
  "BOUNCING♪ SMILE!（DJ WILDPARTY Remix)": "V7uxUNtkXcM",
  "BRAND NEW FIELD": "5PUeKwVQw8g",
  "BRAVE STAR": "aYunqXxmL-E",
  "BRIGHT SUNNY DAY": "psmxw2x6H8Q",
  "BRIGHTEST AWAKING": "kDO1eXhZVJo",
  "BRIGHTEST WHITE": "yAmNJP92Xrs",
  "BURN BURN": "lbaRPnwsfP4",
  "Baile Apasionado": "LKink_i-NSo",
  "Be My Boy": "B2Q8n0DecD0,fenlOInsxMQ,w-B0avzcyjQ",
  "Be Proud": "ldxFlm6iilo,FPiwF4Fl61E",
  "Be my Boy (nyankobrq Remix)": "fenlOInsxMQ",
  "BeSide EMotion": "Bf4tSurwqv4",
  "Beat of the Night": "QEvf1LwmGCA,gvyaqCT5CDY",
  "Beat the World!!!": "ijMaCvz4oGo,KDsROLJQJJc,QGNNNhoJKsk",
  "Beautiful Believer": "DiZfuPy1HYE,mwTxsQ5L0e0",
  "Because": "IfMbiy6KN0k",
  "Before long, DELIGHT": "-33clqK1_PY",
  "Beginning Tomorrow": "YDbYaPyTweE",
  "Believe": "",
  "Believe Clover": "",
  "Believe my change!": "dL2OEsGyGFo,2CDBEaSHRa8,PjT37P4HfyM,TwmDHn-Qa6k",
  "Believe my change! (TeddyLoid Remix)": "9-7PvOMZXEA",
  "Berry Berry Lady": "vRMWpa9x_rs",
  "Best Friend": "",
  "Best Wishes.": "72gAVdKmLBo",
  "Bestest!!": "QlkxvO1rSNA",
  "Bet your intuition!": "CsQdNLkDsRc",
  "Beyond My Destiny": "V6NJaW99rsA",
  "Beyond The Dream": "RMK9W7iDwqo",
  "Bigバルーン◎": "l4Q0Pwj9haY,xrmjWnDtAp0,ovYdbWlZUeA",
  "Bigバルーン◎ (KO3 Remix)": "",
  "Birth of Color": "Own63Wg6zps,DxyCwpQ_zTY",
  "Birth of Color (KiWi Remix)": "Own63Wg6zps",
  "Bitter Sweetアドレセンス": "iZvIp7-uaqA",
  "Black Reverie": "0NJqn4oPqoE,-zif1Q4fAIw",
  "Black★Party": "9wT1huMPCE4,DKakYB5mR7U,udIAUcegEgw",
  "Blessing": "KJH5ryjDr9k",
  "Bloody Festa": "sqCMFtdj0r4",
  "Blooming Days": "NbY9COAPNVA",
  "Blooming Star": "1LJcnF2ncP8,jCzD9M_9MAY,eLNZ5BqZKok",
  "Bloomy!": "3qXgElhYcDQ,-NWULtqoal0",
  "Blue Symphony": "VMqMkrvS76k,gZjT1VOCWzk,uzUU6rXRSEs",
  "Blue Symphony (TeddyLoid Remix)": "gZjT1VOCWzk",
  "Bonnes! Bonnes!! Vacances!!!": "e3kNixxZJMk,QLG3bLaAw2s,0WO6EbIR_r4",
  "Boom Boom Pow": "hORfx2kCoDI",
  "Border LINE→→→♡": "sE-s1nfVBQ4,se9RdMTdq_c",
  "Borderline": "vJZMbto24YE",
  "Bouncy Girl": "oN3R78I9Tuc",
  "Brand New Day!": "-5rMZJFfWL0",
  "Brand New Theater!": "gfHonmWUXJQ,u7oIKQB_77w,H3lO-juQIns,RhtRWA-Sw6A",
  "Brand New Theater! ～Brand New Year Ver.～": "2QZBYW0BpsQ,EiPpjeKrxWQ",
  "Brand New Wave Upper Ground": "",
  "Brand new!": "bCsjPsT6KRU",
  "Brand new! -emon(Tes.) Remix-": "6Rt6n7cH_Q4",
  "Braver Beat": "Ht8mGhi0RWM",
  "Break All Time!": "llqOm_LuXjI",
  "Break Chain": "ZdDb8aJKhSw",
  "Breaker": "R7UjuojWlbs",
  "Bright Blue": "67bgK3LMkD4,MYWSKGUrUNw",
  "Bullet Ride": "Ai1tIsnWdNs",
  "Butter-Fly": "PUJpUotT-Kc",
  "Buzzstyle": "",
  "C'mon! Join Us": "Siq4jJ1RFMY",
  "CALLING": "8ddp8zQp524",
  "CANDY UNIVERSE": "jTGkhDeBGZM,heYJOeg_xfs",
  "CAST A SPELL": "6J7Pbu-SknU",
  "CAT CROSSING": "PYpc2H7C3Fo,m8rj6CssFVY",
  "CATCH ME IF YOU CAN": "yZ3jYqAjdRE",
  "CHANGE!!!!": "DeedT_Aao3c,IUMrJloW5QQ",
  "CHEER UP! HEARTS UP!": "gBBczG_N4XY,DNnDjQIf-94,ORYt4pJklxg",
  "CINDERELLA NONSTOP MEDLEY -DJ KOO Mix-": "",
  "COLORS": "wQPBAxFQo9Y",
  "COLORS ON CANVAS!": "pUAgtQ1MayY",
  "COOL SENSATION～絶対Need!～": "Ujh8pV9lENE",
  "CQ": "xy9B2GKnjPU",
  "CRAZY GONNA CRAZY": "h9V6QmACld4",
  "CRIMSON LOVERS": "Vc50UGrOqoc,Bd-D8-A9tSc",
  "CROWN US KING!": "xegjMTnHB9M,V1HTpQQv9ww",
  "CRYST@LOUD": "qjUMwvzLEIg,d9FfF0SkIf0",
  "Café Parade!": "Nhc3PJZivac",
  "Campus mode!!": "O8CPTwwbvBA,bu1IuUqMQjU,7HL63dr2ldo,RJans9d0vjU,ZFs5pMGmTbE,dHDwtkXsxlg,zPj5hg_Kw7Y,-pF31FOx104,KPwQvzlJ2Kk,RmzAE9bBDic,AvYHAaOOck4,rMZ69k0xP4k,3DxtOY8wCYw,ykc7Rx7cggE",
  "Can't stop!!": "bCJ_VGmqCMU,O8TF8ETHMe0",
  "Casually!": "Mr0Nrj28p0w",
  "Catch You Catch Me": "VXcfwWqR6t0",
  "Catch my dream": "oGcEt2QoiTc,HAi45zq1XhU,W1HvhUo_RzE",
  "Catch my dream (チバニャン Remix)": "HAi45zq1XhU",
  "Catch the Breeze": "bMKlDwuzQms,D8Jv1we451E",
  "Chai Maxx": "hBtbMq-s1sc",
  "Change to Chance": "B6icpS3zzJ0",
  "Cherish BOUQUET": "dT2ooM3fciY",
  "Cherry Colored Love": "3NAey1kgAlk,bZHuOjAGVVg,OrWo0sbC0W4",
  "Chocolate Special": "tddhBUsMEo0",
  "Choo Choo Choo": "X5nendpiPgo,hQCUvsLFpQQ",
  "Clash of Colors": "Xi-frj-wQ3c,e0dt0GkMF0A",
  "Claw My Heart": "1Hq0WwHfqkM,cXdnHIe2IOU",
  "Clean.Clean up": "4T-khJ2WrG0",
  "Clock Hands": "aS55qClDT8E,mSe6PTkl_V8,YdlS_7IXMC4",
  "Closet Fashion Lover": "",
  "Clover Days": "wMy_hG4tprw",
  "Clover's Cry 〜神と神降ろしの少女〜": "0UHvj0v-7fs,VnUPoR4yMTo,wLhxAJJAwBE",
  "CoCo夏夏夏　Holiday": "EFxzmmVi_B0",
  "Coffret Comet": "9WgnaF57jdI",
  "Collier De Perles": "YBNLapFXns0,dj0CL_nJSLI",
  "Color Days": "WNr5sibgr74",
  "Colorful Days": "v8z-Jbf7hPM",
  "Come on a Tea Party!": "GgWYEGsdocc,XV1l2w_tXiE",
  "Come to you": "MIRIUDeiY7o,ZS1yZ2ZRV14",
  "Coming Smile": "DoWwW3KZUsk,RXI9rpROmnE",
  "Compass Gripper!!!": "mC720Vk44FE",
  "Connecting Happy!!": "sZHhgmlhcYc",
  "Contradiction": "",
  "Contrastet": "ObBenbedC-8,1KirGWkJZLI",
  "Cosmetic": "gS63yuCmW50,-F2atEfFnF0",
  "Cosmetic (REDALiCE Remix)": "",
  "Cosmo Cosme": "_hmwEzbR8ZA",
  "Crescent Maze": "",
  "Criminally Dinner 〜正餐とイーヴルナイフ〜": "qnQBsqbaQVg,C8ppomIc6io,_ZRvTHAH65o",
  "Cross the future": "pESzoSel0Z0,1aLjVcddyd4",
  "Crossing!": "2JvuzPO_1yY,AIcx_mxms5M,c97tLMSTJu0",
  "Cut. Cut. Cut.": "Um_gmXaLmsc,iN4iCJWwCQs,EPZSqb-Vacs",
  "Cyber Parkour": "25Su6jUeLDc",
  "D-ark L-ily's Grin": "gF5jJDCoReI,oiTd0BjHo7E",
  "DATE PARADE!": "fD17hAJ2gt4,hyNT3BdC9UI",
  "DAYDREAM LOVE": "jkg10yrznU0",
  "DEAD or ALIVE": "",
  "DELIGHT": "DVDmjrEQoIk",
  "DETECTIVE HIGH! ～恋探偵物語～": "oaaFQzHpTuY,Q6g6ZtKf_iw",
  "DETECTIVE HIGH! ～恋探偵物語～ (Giga Remix)": "oaaFQzHpTuY",
  "DEpArture from THe life": "Eugui_ZSGU8,D0uOynlIRNs",
  "DIAMOND": "uWHB-eKf9Eg,_o1xko0rwIY",
  "DIAMOND DAYS": "_tUrzljNWlU,IREj-bJ1TK4,9zoDjxjg6-c,XsJ8Zv9CdR8,I7l6wYxOLnU",
  "DIAMOND JOKER": "aPNa6Bg-qoM,vgMCBG9XV1U,Ivht80KDexo",
  "DING DONG": "",
  "DISCOTHEQUE": "Ek3epYtlLRY",
  "DIVE TO WORLD": "GZaiOr8g5p0",
  "DIVE to GRAVITATION": "Piz_OV5f1Kc",
  "DNA狂詩曲": "UVCsnyEL7DA",
  "DOKIDOKIリズム": "nhY8EF-qyAM,NrBHaKMHevw",
  "DOKIDOKIリズム ～For Chieri rearrange MIX～": "",
  "DRAMATIC NONFICTION": "GjJf11V_EWc",
  "DREAM": "",
  "DREAM JOURNEY": "exa0hV31jko",
  "DRIVE A LIVE": "TAdI5WpP_L8",
  "DYE BAD DAY": "eKBo7PmR37o",
  "DYNAMITE FEVER MEGAMIX": "Va7u91zfMyE",
  "Damascus Cocktail": "pFcI1EnlWug",
  "Dance in the Light": "JYWANedsRSc,oCKyHiWYuqM",
  "Dance in the school!": "nwKe4_xT0l0",
  "Darkness": "NEVm9b1Q7F4",
  "Darling you!": "s9hVEtYkcz8,IEaRXrCAQvs",
  "Day After “Yesterday”": "Bb2jXxM4lWg,08TbEE84H9k,n8XMXiR3WT0",
  "Day After ”Yesterday” (yukiyanagi Remix)": "08TbEE84H9k",
  "Day of the future": "oYwpD8FmKMk",
  "Daybreak Age": "IljwYgSAXDI,p9Zab9wvVjw",
  "Dazzling World": "",
  "Dear My Dreamers": "VdbXpcEIDUw",
  "Dear My Friend": "",
  "Dear My Light,": "qFG7PNMkC2w",
  "Dear you, Cheers!!": "BTUP8IAkEV4",
  "Decided": "Ctpr3DbnZEo,W28EAcRVEdY",
  "Deep Re Paradime": "",
  "Deep, Deep Blue": "CpLyba26veA,UqCzzJ1yd38",
  "Delicious Delivery": "8NtHO3OekvQ",
  "Delight Excursion": "KcRVgPpbZbo",
  "Demolish": "mnzCYXGBOBg",
  "Destined Rival": "O2Pcd-FnQ0k",
  "Destiny": "XDSPECaTAUE",
  "Destiny -太陽の花-": "XDSPECaTAUE",
  "Determined Soul": "tHY2RUMdPlc",
  "Diamonds": "VIEtRT7Apn0",
  "Discord Area": "801nsXXbnGc,My1hBNsureA",
  "Do the IDOL!! ～断崖絶壁チュパカブラ～": "IvNZ7-p-3qM,6ciWHbWkZ6A,QaJQabO9Q_Q",
  "Do the IDOL!! ～謹賀新年リミックス～": "",
  "Do-Dai": "fY9AndNTGys",
  "Don't U Worry": "",
  "Dramatic Anthem": "PRgKY3l8UBA",
  "Drastic Melody": "0MaTxF236YY",
  "Dreaming Star": "2ilPA7YmPSM",
  "Dreaming of you": "JYkq1mjXN0U",
  "Dreaming!": "CSEmFAR8gmQ,mv1UDSZI6kM,wXBkhynYGXU",
  "Dreaming! -MR remix-": "qx4LYC2XTmU,HAcSCUDPvUI",
  "Dreamscape": "npitUrwx7b0,65jUONWrk8Y",
  "Dreamy Anniversary": "fHn8sc8fLdI,dZdqLs0BPYc",
  "Dreamy Dream": "435rm3tKCzk,_BqL3KpH9C0",
  "Driving My Way": "CQWtY54Cwbg,w8DZNFSMuTY",
  "Dual Style Idol": "e_JxCIXKJRg,U2vrlsXqCD0",
  "Dye the sky.": "4tryVs4ZAl0,Y_69jp58e5c",
  "ECHO": "oOYmYwjrKDo",
  "EGO": "-6ukHEaeBzU,NSuBPElm3FY",
  "EGO (Nor Remix)": "",
  "ENDLESS DANCE": "j38KXTf08Rs,7ebkkWncYdk",
  "ENDLESS TOUR": "lQT3cnIjDtY,WBBz8SpHT2s",
  "ENDLESS TOUR -MR Remix-": "",
  "ENTER→PLEASURE": "JSbweQCQv_c,UkLGLRMJOj4",
  "EPHEMERAL AЯROW": "cMD2myLmbGI,1JFZ9ukJ8Fw",
  "ESPADA": "zI9BqrkekCE,7fDHS6GN5_I,oGj4GKM9fX0",
  "EVER RISING": "PQC5jiQagCk",
  "EVERAFTER": "mNZXAWvV_44",
  "EVERLASTING": "uZuqmwhljVo,9zpueafGU-o",
  "EVERMORE": "ELUXC9lswFw,V3EUp377NE0,HfNb5OtlJUk,fLBw2a65qXs",
  "EVERMORE - しんげきRemix -": "fLBw2a65qXs",
  "EVERYDAY STARS!!": "_7GEimKTPb0,8hsdQWUrrd4,RdOrfTS1MAQ",
  "EVIL LIVE": "eCtFNaTWG2Y",
  "EXCAVATE": "",
  "EXCITE": "mf_gyR0MZ10",
  "EZ DO DANCE": "",
  "Earnest": "77R1tMn_9WA",
  "Echoes My Note": "YYWCtVCHrcI",
  "Eclipse of the Heart": "ldaQpMNJRL8",
  "Emergence Vibe": "U3tfGQZ8Mfc,S8_WtPIkw8Q,6MSnlqFIIZM",
  "Enishi": "4a5CbhagoTE",
  "Enjoy & Feel": "r__FyUT39vI",
  "Episode. Tiara": "K5yqoOYsaQM,eOwx7S0nnN4,icMFQ75A9Jg",
  "Especially Angel♡": "tsLSSDaeQ-c",
  "Eternal Fantasia": "us7Dw4_Pt70",
  "Eternal Harmony": "RD3-eS0gt40T0,LAjE2_Yb3SE,45-NOYrinL0",
  "Eternal Harmony (チバニャン Remix)": "LAjE2_Yb3SE",
  "Eternal Spiral": "X1tJG1zSenA,V08Jrsa50BQ",
  "Eterniteen Age!!!": "30YOlpCg3JI",
  "Ever Sunny": "U31LWmo5m0g",
  "Everlasting": "HIpf6yrRx9E,556ijFeHpgs",
  "Everything": "",
  "FAITH/TO/FAITH": "e_KMa7ntMEs",
  "FAKE SELF×TRUE SELF": "2eA581UgaRw,GKNaO9s_AKE",
  "FAKE SELF×TRUE SELF (Sober Bear Remix)": "2eA581UgaRw",
  "FANTASTIC DISCOTHEQUE": "S2mcm1p6b6k",
  "FELICE": "6SP2DOCIjqY",
  "FIELD ON ME": "EnxMHX_6LpU",
  "FIND YOUR WIND!": "fYYq1Itx8DI,S1p9OKMG0SY,mFzN8ccO80o",
  "FIND YOUR WIND! (TeddyLoid Remix)": "021miKCCxIM",
  "FIRED UP!": "YOzaIOmYb_0",
  "FLASH LIGHT": "590QDGcsG0Y",
  "FLY TO EVERYWHERE": "yajhaCNkSwI,gJYo9Km2gkE",
  "FLY TO EVERYWHERE (Getty Remix)": "yajhaCNkSwI",
  "FO(U)R": "",
  "FOCUS ON YOUR LIFE": "izKQEiF1ZVg",
  "FUTURITY SMILE": "0hYVEG5Abfs,ZkMfLOGXcoI",
  "Face the World": "jab-gCr9eEo",
  "Fading Stars": "EZXKNYoERHg,VG3jFqk051g,0HdctmZ-xK8",
  "Fairy Daysは絶え間ない": "lS71DVb0aOQ",
  "FairyTaleじゃいられない": "3ZMdF3bhJR0,cOIFkaay6Bs,aAEYB8grpCo,lvT4dP2PsmU",
  "Fantasia for the Girls": "FJNZVe4SnzQ,uNQ8ueOBNfM,pLQJjMP7LRk",
  "Fascinate": "",
  "Fashionable": "xj3U7rxLU7A",
  "Fate of the World": "9dtD_JCp3NI",
  "Feeeel Gooood!": "LzwduUxqQiQ",
  "Feel Jewel Dream": "Ah6qBoXzqEU",
  "Feel Jewel Dream (James Landino Remix)": "",
  "Fermata in Rapsodia": "OIMPGm7xS_A,Bi_fbsjRH5E,6rzlYpq8m6w",
  "Fighting My Way": "T1GK55fsIhw,nA1Zqxbnq_o,H_f_SZ-I0C4,4ALFjALIc5Q",
  "Fin[e]〜美しき終焉〜": "ICMWfMA8U74",
  "Fine Day! Find Way!": "h9YPHqazML8",
  "Fireworks―Wanna Be A Star―": "x0DL-sdTVl0",
  "First Stage": "A6HCX1SDY8U",
  "First Step": "",
  "Flip Flop": "Yv1XS5zsbuQ",
  "Flip Flop ～For SS3A rearrange Mix～": "ireWQZmPUig",
  "Flooding": "rHHiw84DnWI",
  "Flowing Freedom": "ZLU_hSa6dIw",
  "Fluorite": "4AcOcsvGluY,lZ6HNbbc2qk,SF5_pCD0owM,4TchmSegna0",
  "Fly High!": "",
  "Fly and Fly": "BITX92KQfX0",
  "Fly me to the moon": "C6JI2L1QTbU",
  "Flyers!!!": "O7zMActeP1A,IDQ3KN05xPU,fmZ8fz8eK7E,m8k72NoLdzE,kmRAbPj7ZUU,uDPwu2Pudb4",
  "Flyers!!! -MR remix-": "C4kVBFgb-3I",
  "Flying Hawk": "sIUjNijasiU",
  "For フルーツバスケット": "",
  "Forbidden Paradise": "JMtW1EU0nFA,vg_-XmZ76ZM",
  "Forward March!!!": "c8MhxsmjbKI",
  "Fragile Heart": "AzUbM5_b7Lg",
  "Friendly Smile": "Iy3SC3WJ_-A",
  "From Genius": "HB47hmnGkc8",
  "From Teacher To Future!": "bb5xxdPc2J8",
  "Frost": "21lcHormO2I",
  "Frozen Tears": "gBFgHLC-9S4",
  "Fu-Wa-Du-Wa": "PtUpva6XlMQ,4zlu4OfZSts,Ee1-FQJIkJw",
  "Fu-Wa-Du-Wa（チバニャン Remix）": "PsC6oofb7g4",
  "Fun! Fun! Festa!": "LMDPPn9U5eU",
  "Funny Logic": "FLjlslI2hxE",
  "Future Designer": "pKKh7_5n9Og",
  "Future Transit": "bsy75Qwl56w,sA_Ne-6hPm8,w2ZMMZhWB1o",
  "GEMSTONE": "mQ4CqDiGRJw,QuFkKeRv5m4,IerSHRMGbmU,qZJtT3NLWv0",
  "GET OVER": "W9fQvU1mwoY",
  "GIVE ME × FUSION": "BilSOqyWvGI",
  "GLAMOROUS SKY": "wKgMJQrMaNg",
  "GLORIA MOMENT": "7y8eZ8u5l58",
  "GLORIOUS RO@D": "v6mq5vPXDWA",
  "GO AHEAD SMILE!": "5t45PIxgf1g",
  "GO FOR IT!!": "0EasVbuNv9E",
  "GO MY WAY!!": "x0KzJYb7kCo",
  "GO NEXT": "HRo5_fdCkmY",
  "GOIN’!!!": "jDJyO7x4CEk,fGPEZ4LmKiA,cQBP8LdywHY",
  "GOLD～No.79～": "fj2sbb8hhzY",
  "GOOD NEW MORNING": "D7JTIFb3HGk",
  "GOTCHA": "D13eaPWqj5Q,jCwcC_ArsEU",
  "GR@TITUDE": "guUKihbNlWs,PzKGs7O-_5I,SMAz8Ojwf3c",
  "GRAND-NEW UNIVERSE": "LYxUr2csZK0",
  "GREEDY GIRL": "iLsmArtrPq4,z5FYbAEffAw",
  "GREEDY GIRL（ケンモチヒデフミ Remix）": "EfnabfY3eqM",
  "GREETING CHARM": "IOy8P2ChqD8",
  "Gather Round!": "nrXZuQDQBhg",
  "Gaze and Gaze": "0UmjQUXAIjQ",
  "Genesis Contact": "qW1_rWhyZnI",
  "Genuine feelings": "8xfz3NO5jRA",
  "Get My Shinin'": "xRAtT1V9Nj8,3z5Xe3b1K0s,YRVPrCMXXY4,dXWwMVsXbp4",
  "Get My Shinin'（DÉ DÉ MOUSE Remix）": "YRVPrCMXXY4",
  "Get lol! Get lol! SONG": "05uItuNmFyU,UeP2mB_YIlo,736lhs3hm38",
  "Gift Sign": "vxz-BqLhIO8",
  "Girl meets Wonder": "7ahuwjSrQm4,logGOQ-DKRI,6Uiw9V2SXsk",
  "Give me some more...": "zBU9OKlDseU,rjn-4vBvFDI",
  "Glass": "7A2gsj8lL-E",
  "Glow Map": "PcxH44XwcEg,vhXp-7L3vkU,a4ahwwmegZk,Zohqvo8BWoc,7h--n8dayK8",
  "Go Just Go!": "fdFKvkA51b4,madTG2X38IE",
  "God knows...": "8c_0G0OjZd0",
  "Godspeed IGNITION!!": "plo6OIvd6HY",
  "Going my way": "y8h3Pxdlc3s,Kg7IV80d-Aw",
  "Good-Byes": "RZLFgE_jT94",
  "Good-Sleep, Baby? (DJ WILDPARTY Remix)": "RZLFgE_jT94",
  "Good-Sleep, Baby♡": "SuGn7YUoVW4,TTGcrVY1_fE",
  "Gossip Club": "",
  "Great Journey": "KM3nBrV9aL4",
  "Great Sympathy": "v31yVm24lJ0",
  "Groovin' Magic": "",
  "Growin'Groovin'": "q9djdC8L3bk",
  "Growing Smiles!": "uD0_W-XAueU",
  "Growing Storm!": "eSBn3WtCwY0,k1YLH-7o7hg",
  "Growing Storm!(TeddyLoid REMIX)": "eSBn3WtCwY0",
  "G♡F": "pFLQoseZcko,yh11IkF5Hf0,x9ELGKdLRVw",
  "G線上のアリア": "",
  "HALLOWEEN GAME": "VxYr4YJcbZw,7p0MFz1NMtI",
  "HANAMARU LIFE": "j-V5utns3wI",
  "HAPPY STARTING": "",
  "HAPPY×HAPPYミーティング": "lpoJp5uo3hY",
  "HAPPY♪STEPPING!!DREAMING☆": "lTcoHZGULqM,Z8Y8MVJ5R7I",
  "HAREBARE!!": "LwIKgiJ3u6A,pBrIg0zA4Zk",
  "HARURUNRUN": "SQftfxZe77Y",
  "HEART AND SOUL": "",
  "HEAT BEAT “Identity”": "9FDCj4TPp7k",
  "HELLO, YOUR ANGEL♪": "MJA_i8kqgxA",
  "HIGH JUMP NO LIMIT": "fP6CEWiA15g",
  "HIGH PRESSURE": "",
  "HOME RUN SONG♪": "XDZ4ALvxwQM,uCWumAa7Jvg",
  "HOME, SWEET FRIENDSHIP": "QwmHufiqUfw",
  "HOME, SWEET FRIENDSHIP（Batsu Remix)": "azTPVGe49Bk",
  "HOT INSPIRATION～世界のテッペンYeah!～": "4RZYv00fxYM",
  "HOT LIMIT": "",
  "HUG": "a50vKpZhYTo",
  "Hacking to the Gate": "cLNtti90PU0",
  "Hallo, Freunde!": "iI5bUeOXjrA",
  "Halloween♥Code": "hDHVJt68j6A",
  "Hands&Claps!": "YnzQ0E-rfJ4",
  "Hang In There!": "YhCppOaNXes,1O0yM1zZdwQ",
  "Happier": "zB0ismDvzzg,R3xelzEB7Rc",
  "Happy Christmas": "-C86KaVmrq0",
  "Happy Darling": "UuP6hb6r9mA,DSLA3qPdSZg,hTBGZLAzfVg",
  "Happy Darling (Giga Remix)": "SpmdZe9kLl8",
  "Happy Funny Lucky": "uMY_qIoWgnk",
  "Happy New Yeah!": "gGpax-8blMw",
  "Happy!": "mHSrb_J6Xls",
  "Happy's Birthday": "4pNT3deLE5c",
  "Happy-Go-Unlucky!": "aDftsVLqokk",
  "Happy×2 Days": "RX6y1BOg3qM",
  "Hardcore Toyworld": "Q2YymJK5WK8,sbCcdQnDi2w",
  "Harmony 4 You": "_UyFxiEEh-g,MGbPgOWgQ1A,fHW_Q-EyyGw,-KJjIb-hrcs",
  "Heads or Tails?": "gpvZiI3PTcw,bQZw4JzZnhI",
  "Heart Voice": "WWo_z7dwKYA",
  "Heartmade Cookies": "ApBduH9NJl4",
  "Hearty!!": "bDhOZ8Ngcd8,4jSsQcbxGH4",
  "Heart♡・デイズ・Night☆": "VMGbAabGK4Y,vuqQcbAtCGw,p42nox25bnI",
  "Heart♡・デイズ・Night☆ (TORIENA Remix)": "vuqQcbAtCGw",
  "Hello Especially": "nHDL7kAGpZE",
  "Helloコンチェルト": "e71pDK91Z2w,z0hoqdn7m8M,vVeWz-zOyx8",
  "Helloコンチェルト（チバニャン Remix）": "mk7RIRDsf6Q",
  "Here we go!!": "Qpf-U6AJ0QU",
  "Hide & Attack": "Fk1NobIWGvg",
  "Home Sweet Home": "2VrT8I19pfk,iL8kJCLTF1M",
  "Home is a coming now!": "rwt2pzPtM4o,AggolIx7FQc",
  "Honey Heartbeat": "-jXX7jAklTI,GpUyGmEFZ88",
  "Hope's Journey": "bHKgYVdkOPg",
  "Hotel Moonside": "kU5ii7DAyxU,1prjVlHtp60,gap3q_l5BDc",
  "Hotel Moonside -Take me away from Metropolis Remix-": "NCaslKjG3Hw",
  "How do you do?": "",
  "Howling over the World": "NBJ67a459u8,qcAroypk8oA,6c8fuKq77dA",
  "Hug a nice day!": "2uxXKO-FukQ,X44t1Y4G35g",
  "Hundreds Color": "7ACJQzHXfEY",
  "Hungry Bambi": "OPVhc2v9w3Q",
  "Hungry?": "COEBVg-_NVA",
  "Hypernova": "vTqCNHRe5uA",
  "I DO": "N_9wyBXzQag,DxN3-mJ8q98",
  "I Want": "hplR3D2Vwmo,QoTnTCHax3s",
  "I Wish": "2kaYaGNW9Pk",
  "I did+I will": "jY-o0dbAwOg,cyKnXtmb5l0,N6XQr_s1WFI",
  "I'll show you": "sOxso4ZPucc",
  "I'm so free!": "",
  "I'm yours": "13KoKXQP5i8,Mdboap7m_EM",
  "I.D ～EScape from Utopia～": "H435h9XC1wA,Cs77ecDsMyo,QAD8K4IYYoA",
  "I.V.": "y_mKofHAwU8,Ay1iS1fpG8E",
  "ID:[OL": "",
  "IDOL POWER RAINBOW": "",
  "IDOL☆HEART": "dEEdQwBchxs,1cQVgBeBN-4,SHDhmLlXxpg",
  "IGNITE": "M9jGdOvXC5M",
  "IMPRESSION→LOCOMOTION!": "K0rCU1uyq_U,q5Cznnpuzk8,qskn0OISxIA",
  "IMPRESSION→LOCOMOTION!（☆Taku Takahashi Remix）": "q5Cznnpuzk8",
  "INTERNET YAMERO": "GzFpi37fk3A",
  "Imitation Ghost": "tk4TBY5MlU4",
  "Impervious Resolution": "ZCbOTSAlTXo,UmMkOFaOMNk,1WD_8IlrW48",
  "Impervious Resolution (TORIENA Remix)": "VcYJviBec_w",
  "Infinite Octave!": "s0RfozpOiO4",
  "Inner Dignity": "Ghk0XbsEDTM",
  "Inspire": "",
  "Irodori": "nQAyuWZzBGA",
  "Is This Love": "",
  "Isosceles": "pR0zFFU67Ps,6RMoG_z_aJw",
  "It's ALRIGHT!": "",
  "It's show": "",
  "JM―Justify Myself―": "",
  "JOKER↗オールマイティ": "LobeN4p-aB4",
  "JOYFUL HEART MAKER": "7X8nSOs0Zyg",
  "Jet to the Future": "fl79_0kdsHU,fwq3nMTGA8E,iRSlYdTPFGk",
  "Joker": "sJyeI1c5edc",
  "Journey JOY Blend": "jIuiQkTQpq4",
  "Jupiter": "",
  "Just Us Justice": "qMBvWj7AAnY",
  "Just be myself!!": "JpQg-xKpmpY,9yc5FuGrPCY,mce1fyXN2So",
  "Just be myself!! (Dummy Dog Remix)": "9yc5FuGrPCY",
  "Justice OR Voice": "5yw74sJQDWk,tdVng-3uQYg,EDA1Zjm1q1o",
  "J☆U☆M☆P": "",
  "K.now O.nly": "7kik47wJioI",
  "KARMA": "S9oyN6RHAR4",
  "KAWAII♡めたもる交響曲": "bADPhUD27B4,VxPRXKxEn3Q",
  "KAWAIIウォーズ": "v7I38Zjf5wU,C4Kdtyfz3eE,OCFK0dNCUtk",
  "KEY to the DREAM": "76eZHPVsmLA",
  "KING of SPADE": "8adhyYTkYGk,3pNifgTTgDQ,xXsHKPquKPg",
  "KISSして": "JVhV2WjlR24",
  "Karma": "cNHnE8ZyVJg",
  "Kawaii make MY day!": "mU9aCPPdsvM",
  "KiRa-KiRa Sensation!": "eQhgI8Nk8rI",
  "Killer×Mission": "xpuaUQ-i1mw",
  "Kira Kira": "FWHYvQ12HN4",
  "Kira Kira (r-906 Remix)": "",
  "KisS": "zQ_KnL3fOSM",
  "Kiss Me Good-Bye": "",
  "KoiKyun!": "DPrb0GhYlIw,5RK2isTh25I,qCCKttskgq8",
  "Kosmos, Cosmos": "ALDDbt5YJ8s",
  "K・A・W・A・I・I of the WORLD!": "YNRplFZWiRs,IgtNZrTjtPQ",
  "L.U.V": "QyGGKXK_t_c,CQ-pxYTwCoI",
  "L.U.V (石濱 翔 Remix)": "",
  "L<>R": "",
  "LEADER!!": "v7B-2rctw88,tWZqvmI1IJ8",
  "LEADING YOUR DREAM": "BWwUDjJo90s",
  "LEMONADE": "0I_3jP4BahE",
  "LET'S GO ALL THE WAY!": "",
  "LET'S GO!!": "L8uK_SQXhko",
  "LET'S HAVE!": "3fYAzAt1dNI",
  "LET’S GO HAPPY!!": "JoLyKY01a3A",
  "LIFE": "BeUw_dVufbs",
  "LINKs": "y-gTmIrwMrY",
  "LIVE LIVE LIVE!": "qqyTvgd8ncA",
  "LIVE in your SMILE": "q75Sl6ZVf4g",
  "LOOK THE SKY": "",
  "LOST": "",
  "LOVE & PEACH": "",
  "LOVE 2000": "",
  "LOVE is GAME": "yYpNVOhB_2w,4reICKY1_6I,zK1mg7xOKYM",
  "LOVE&JOY": "",
  "LOVE☆ハズカム": "vY_Qn_DByd0,OQ6txlYc788",
  "LOVEオーダーメイド": "IhQpJ_sQQig",
  "Labyrinth": "",
  "Lady☆Cake": "",
  "Large Size Party": "BQoefCO0wuM,oeCbyrOGkH4,kKOFADXf0YI",
  "Last Kiss": "1sx9JTbDlKQ,46NGUe8XNSc",
  "Last Kiss -ESTi Remix-": "MHyM9J0JlDM",
  "Learning Message": "xwa9MY7fh1E",
  "Legacy of Spirit": "im62ihtnUNs",
  "Legend Girls!!": "QazBUfjktCM,IaI8zYUrK7g,j77jsluhsTQ",
  "Legend Girls!! (fu_mou Remix)": "IaI8zYUrK7g",
  "Let's GO!! ICHI-NO-NI!!": "iwD2bg2j4k0,Fgvx4c9UHjE",
  "Let's Sail Away!!!": "eewtkTSOXvA",
  "Let's get a chance": "cXERsDyCXHE",
  "Liar's good bye": "cB7nvh3XrOk,TdU-Gp2JUjQ,zhKmfZvWe3c",
  "Liar's good bye (TeddyLoid Remix)": "TdU-Gp2JUjQ",
  "Life is Beautiful!": "aEUzhUGA-NA",
  "Life is HaRMONY": "MtSB-iZJW2U",
  "Life's Side Menu!": "dtzL1-YfrNU",
  "Light Year Song": "DK4ziGE0J_Y",
  "Like a Rolling Donuts!!": "w-TSc_J63Sw",
  "Like twinkling STARS": "u-oP11fRGVc,LLQ7m-l_7FQ",
  "Lit up my sky": "eP88S3lZ_54",
  "Little Match Girl": "Fa7Hd3Cef8g,i9MGEUMnZHI",
  "Little More": "Sf4kT2oinWo",
  "Look up to the sky": "IYjbadrSTCI",
  "Looking For Love": "",
  "Lost Princess": "Fa11Oxki5a4",
  "Lost my music": "8Ts9wSrxgIQ",
  "Love & Joy": "YzBr_c61TsU,hPJCFWH7cPI",
  "Love Addiction": "f3fHCDNwTng",
  "Love Letter": "I4DgzO1rI18",
  "Love∞Destiny": "rw7aJxRnq_8,NrBQMj1wdrg,xkJEBNuBKTA",
  "Love∞Destiny -Jealous prisoner Remix-": "l2xEYUmJ-XI",
  "Lullaby for Armors": "evre6OSnAHA",
  "Luna say maybe": "Sq5Dj0U06vQ,DJOLgiWAqXE,8LNUGiOppTo,NBL9sMFXj1g",
  "Luna say maybe (gaburyu Remix)": "",
  "Lunatic Show": "rZvGKjIJP8Q",
  "Lunatic Show ～For SS3A rearrange Mix～": "S3fr1zab1yc",
  "Luvliminal image": "fohxBp9cpTI,5h-KyyjFdoc",
  "L・O・B・M": "nZZcjXr3fbs",
  "M@GIC☆": "7TUT6Uq7vVM,DEjJ9ZyVyhM",
  "M@STERPIECE": "LhIsmLnYAg4,RLLnXvkIz_8,rxS9AbVvFrU",
  "MEET THE WORLD!": "RnhmlmnhECg",
  "MEGARE!": "dAPGVNlHGPI",
  "MIRROR of TRUTH": "Sp0Ud-_t7V8",
  "MISSION is ピースフル！": "NIsNILUufj4",
  "MONSTER DANCE": "YhZD4PzrXF0",
  "MOON NIGHTのせいにして": "gYHxxAGPmiA",
  "MOONY": "J-JhzjcQ1k8",
  "MOTTO!": "bhxfLPqOMA4,ZK-eioiYXoo,E85z9TxoABs,_Ol0LTVkkUg",
  "MUSIC JOURNEY": "Ne94wydrxGY,QliaxvEH-6k,NUiNKUfz9VM",
  "MUSIC♪": "Bnc8eMx5JbU,HCB3x2gHxCU",
  "MY STAGE": "mR0qtqvRYWM,6erPd7exdEQ",
  "MY STYLE! OUR STYLE!!!!": "Cmv0tVrIbbc,TM2hbEAgMaU",
  "MY STYLE! OUR STYLE!!!!（KO3 Remix)": "3NOU7XPjQas",
  "Made in 「♪」": "StZsQ0rJyUw",
  "Magic of Princess": "6TNg2HNK11g",
  "Majoram Therapie": "V9pKcZwMpug,0MCcdirW4Es,4D04puc-GMo",
  "Make New Legend": "9Udo2pBZHh8",
  "Make up ↑ Magic": "Ld5jXGplOeQ",
  "Maria Trap": "PSY5GJAXVVg,xpY-pfAuSPQ,S8Jei7xFJJ4",
  "Maria Trap (Tanchiky Remix)": "ih9jZSa1JWA",
  "Marionetteは眠らない": "MnBmgj0gtJ0,f2NEbwMr5gQ,UORQ4vI--_w",
  "Marionetteは眠らない (TeddyLoid Remix)": "RglO-ZI3Xzc",
  "Max Beat": "bqUcdQSW3qA",
  "Maybe TOMORROW": "",
  "Mela!": "LiwEWHWNqcA",
  "Melody in scape": "LTfVVnde_Ik,cw68FjV7lbE",
  "Melted Snow": "",
  "Melting season": "",
  "Melty Fantasia": "xPz4f_IKl7g,cNkgjBpxzYw,vskT4w-48QY",
  "Memories": "6xIwvAvdVzs",
  "Merry Warm Bodies": "4x0gYecQ-PA",
  "Meteoric Swarm": "KvNSui50pvo",
  "Midnight parade!": "l0PYSvXV8zA,b1e769b0QWw",
  "Migratory Echoes": "pZFWSNYnxN4",
  "Migratory Echoes (アルストロメリアVer.)": "_McBSbZiXA4",
  "Migratory Echoes (アンティーカVer.)": "9DlhCn_SuCg",
  "Migratory Echoes (イルミネーションスターズVer.)": "s7YvGjutETI",
  "Migratory Echoes (コメティックVer.)": "bPPofGixnS4",
  "Migratory Echoes (シーズVer.)": "rfrNzu1h2Mg",
  "Migratory Echoes (ストレイライトVer.)": "D2ZSLboilqw",
  "Migratory Echoes (ノクチルVer.)": "EB6SL4vv9aI",
  "Migratory Echoes （放課後クライマックスガールズVer.）": "pbgN3qwq1XY",
  "Milky Mode": "jDRvqrD-Cqw,uXnPXijNjMs",
  "Miracle Night": "aW_x8NjDYbM,7nYFSM1lrUM",
  "Miraculous White Day": "-RFL2SzjwzQ",
  "Mixxxxxed!!": "5aF831VDi_I",
  "Mon Chéri": "",
  "Monday Night Fever☆": "fyzkCrlMEME",
  "Monochromatic": "sx6CnJbn33k,mSITQcotcgA",
  "Moon Shape/明鏡止水": "d6a7wf2MpF0",
  "Moonrise Belief": "HlvUrM2LLEo,d1m5MhFTJ4M",
  "Morgana": "RtwXIS3HUH0,VGd43l04jpA",
  "Multicolored Sky": "QASXjAb0DH8,TxkBJTAAbYk,YPUvtjdRczQ,ky7l6HYGjt4",
  "Multiple Entertainment Show!": "HAffw4L_SCE",
  "My Best Friend": "ffx5o4iOLoc",
  "My Evolution": "Op_EfSVW4Z0,Is_hXoOdyx8",
  "My Soul,Your Beats!": "BxyQ50L6G_Q",
  "My Starry Song": "yKqNuz4TLFs",
  "My Sweet Darlin'": "zMHwIQB18J4",
  "My Wish": "rQ2LQnEc-Zs",
  "My pen light, SMILE": "dNl1Qb3RITc",
  "My time": "qhugiBf68XY",
  "Myself": "xR_-aup8xh4",
  "Mythmaker": "G_4G6uGaT-8,VaFzrvFI754",
  "N.O.R.〜Notes of Revolution〜革命についての覚書": "qaozpRXs0eU",
  "NEO THEORY FANTASY": "8ERgZUBi2Wc,jLoeLOvPSY0",
  "NEW LIFE": "",
  "NEXT STAGE!": "J7YqFyXSi9k",
  "NO CURRY NO LIFE": "n4uB0Cc1boU,XIIp_xjuIFo,LwHOyFiyMTU",
  "NUDIE★": "se0ddhdUYe0",
  "Naked Romance": "",
  "Naraku": "jnVkaZzxaZs",
  "Nation Blue": "9Z4cDrdJwrU",
  "Nation Blue -蒼く蒼く蒼く Remix-": "buyMnZMESdM",
  "Near to You": "0e_a9em4uao,jr8ilKycn6Y,_BppLhudI-E",
  "Near to You ～PicoPico D'n'B MIX～": "Z7Jp2L8PfHI",
  "Nebula Sky": "g1Xht3_hB5c",
  "Needle Light": "NZsEp5kIDwo",
  "Neo Beautiful Pain": "mtk9iEZs4Ac",
  "Neon Sphere": "",
  "Never end 「Opus」": "214WGz-pDqyNNL9Z",
  "Never ends": "PgKgzfZRIfI",
  "Never say never": "lsqZ1Ik9QGg,h0E0872IuHo",
  "Never say never ～For Anastasia rearrange MIX～": "",
  "New Me, Continued": "x9PRnuerJig",
  "New bright stars": "ejVvxSL18Ko,T1VrARJ9Ym8",
  "Next Chapter": "EwU0NCGuV10",
  "Next Life": "qDUhwBBHews,3cZ512H-NsA",
  "Night Time Wander": "AA0pq6VeEZA,48zxubsE0qs,lWc59jzJ_NM",
  "Nightwear": "4WM4Bu7kFWk",
  "No One Knows": "kg2ctabUCJk,d5YQFufqXHU",
  "No brand girls": "fCpdEo6syJo",
  "No.8": "gB89fpqSvAM",
  "Nocturne": "atO1FfQDPt4",
  "Nocturne ～For SS3A rearrange Mix～": "ctkCJrw1ZkM",
  "Nostalgia": "",
  "Not Alone": "azvtvszZF9I",
  "Nothing but You": "r7vzkW79liU",
  "Nova Chro": "KLXSdBvwHmQ",
  "Numberless": "_zGfqCdGRmE,5qhwDvazjs4,yB_psXSwlyY",
  "O-Ku-Ri-Mo-No Sunday!": "Fa1YczPNxYw",
  "O-Ku-Ri-Mo-No Sunday! -ヒゲドライバー Remix-": "xDcfX6xaiz4",
  "O2": "",
  "OH MY GOD": "PV44FZwyS5M,5bE4FMBvur0,vnbWkAK4azQ",
  "ONE LIFE": "Oqe5ncut9S0",
  "ONE STAR": "vDosxAnqKiw,QkoLhsHWMVQ",
  "ONE to DREAM!": "jwkUxpoChYs",
  "ONLY MY NOTE": "jMTh9pOSeKM",
  "OPEN the New world": "0Z64xRYP6tU,Xqcd9OkmCEU",
  "OTAHEN アンセム": "nbx8eftV3v0,qvnZFDkCXgs",
  "OTAHEN アンセム -Massive New Krew Remix-": "MSgeNg99hys",
  "OUR SONG―それは世界でひとつだけ―": "tlFtoGK2jbE",
  "OVER THE SKY": "2qZ9Cce9DkI",
  "Oh Yeah!!": "4wafKZJZV_w,HtNlApmB_5A",
  "Okey-dokey": "",
  "Oli Oli DISCO": "-DUlCF98reA,zOVpFX_pCJw",
  "On Sunday": "",
  "Once Upon a Secret": "t7xX7fagpPM",
  "One Life": "-A1y_8PwKJc,uN67NKXwOO4",
  "One Live One Love": "",
  "One Step": "c4br2s0uSvo",
  "Only One Second": "AioTu4GBKMI,M3-CtM8PX9Q,ZHrXUz5toNE",
  "Orange Sapphire": "",
  "Orange Sapphire -ヒゲドライバー Remix-": "",
  "Our Chant": "CNPSxUiqcpA",
  "Our Colorful Stage!!!": "",
  "Over AGAIN": "fIpaEB_i1cw",
  "Over Drive": "",
  "Overdose": "bxPjZBaLX1Y",
  "Overdrive Emotion": "uv3Ud6cojzQ,qJIneWk8sMg",
  "Overnight Sensation 〜時代はあなたに委ねてる〜": "XmoOBeR3swk",
  "P.S I Love You": "73VKprVqqiU,Pwro1nb6Pnk,5m2Tl_b6wC0",
  "PANDEMIC ALONE": "LSlKeBYtJ7A",
  "PEARL-WHITE EVE": "",
  "PERMAFROST": "HAKU2ZiZq10",
  "PLAY FOR FUN-TASY": "ZCaT0P0cQVI",
  "POKER FAITH―ポーカーフェイス―": "fLsOvljEi8c",
  "POKER POKER": "iUORgk_xFaI,aekFxVX3ZVo",
  "POKER POKER (TORIENA Remix)": "_0QYIoiQmCE",
  "POP STAR": "LaPeYN_2DUk",
  "POPLINKS TUNE!!!!!": "16l6dpeuuPg,KAafFf4pXH4,BhSc3TcMyPA",
  "POPPIN' PLANET": "7aXlwpf3euQ",
  "POPPY PAPPY DAY": "WnoQ8PQC7RM",
  "PRECIOUS TONE": "5-PWz3sobDg",
  "PRETTY DREAMER": "JXkwl3rS6Ow,hdwEwY3D9Zs,fIawQQAdtC4,FPQCh1z9Lpo",
  "PRETTY DREAMER（チバニャン Remix）": "fIawQQAdtC4",
  "PRIDE STAR": "4XAK74TYI2c",
  "PRISISM": "tr_leWHLafc",
  "PRIZE PINATA!": "K3Oob3IaESw",
  "PROOF OF ONESELF": "LvU8jWM6T0g",
  "PROUST EFFECT": "RZmtTDW-Y14",
  "PURE SNOW": "cb0U284F_mA",
  "Packing Her Favorite": "O4kr_JhW5mY,RGQIxC8fkpI",
  "Palette": "LhylAoBZurM,x-vKe1A73xs",
  "Panorama's Fanfare": "OWfz0rBPoWQ",
  "Parade d'amour": "p1AatYesOzU,CI36ZUNPz-c,qOM0Un5CamU",
  "Paradox of LOVE": "CAJfqFFtCx0,pQVxzQyVIQE",
  "Pavé Étoiles": "qpQco1B-hsw",
  "Perseus-ペルセウス-": "ok_C_JH4JSg",
  "Persona Voice": "OJu5wsU2OkE,PxVZmHjZR50,CzLH3ipVT5o",
  "Piece Montee": "GQmg-gJi2Yo",
  "Pioneer Impact": "P3k_y8IARec",
  "Planet scape": "D_huCE4HCDo",
  "Platinum MASK": "ooR6UhUOUOQ",
  "Play GO! Round": "gfbYK1PR-9Q,DTNECLVa3lk",
  "Pleasure Forever…": "5pg1WEieoWw",
  "Plus 1 Good Day!": "tmw61fdNnvY",
  "Poison Berry Daughters": "Rc8iM8__90E,uSY3eQlh8oM,08yGaxb6jBo",
  "Pomegranate": "5rWIz1YYiIg",
  "Pon De Beach": "P2lBU26ckW8",
  "Possession Mind": "SWVshy1YOZU",
  "Precious Grain": "Uq782jPuCBE,D8JySWlzDiY,Q9pdOZhEnGM,xsAfp5wIk5Q,cQzOtTwWtiY",
  "Precious Grain (TeddyLoid Remix)": "EKt7Ngdn3vQ",
  "Precious ordinary days": "9fWMZ6lop3I",
  "Present For You!!!!!～A day in the café～": "PnG4Lc-zgAQ",
  "Pretty Liar": "svaJo_ws2UA",
  "Pretty Liar -ミフメイ Remix-": "yQoV3dSEnto",
  "Prima Princess!!": "bBG514O08fk",
  "Princess Be Ambitious!!": "klBlV-NXFp0,3fESck_y7ds,do_JVQZGqXE,h7E5aaGZUR4",
  "Princess Snow White": "",
  "Private Sign": "6nmRVM2loNY",
  "Pu-Ru-Ru": "",
  "Purely&Kindly": "LqPaKWLxj_4",
  "Purple Sky": "Wy9Z8YP1zf0,HJBcLcqe50I",
  "Q&A": "",
  "QUEEN OF THE PIRATES": "q1ICkkxdL-Y,26_djZAVfs8",
  "Quod Erat Demonstrandum": "elE70nwutp4",
  "RAGE OF DUST": "AO3MLAC2_bc",
  "RAY OF LIGHT": "f_eRaxOSXyw",
  "REACH THE SKY": "XK49l2H-aTo,Zqby1eogDio",
  "READY!!": "22RQOgQhwxI,kedHi3xJx0E,AOQ83vSmO7I,oU_dYaKOP4g,hxJplZBbLn8,Ed9siF5ktOQ",
  "REALIZE!!!": "gH9T8LGie2A",
  "RED HOT BEAT!!": "e00Q9P5KZgk",
  "RED ZONE": "5-kSDRDb1qA,7N9xcNRCnwM,fTDahWXcG_w",
  "REFRAIN REL@TION": "nPPaxKtFxeA,8cYN2CcTHFo",
  "RELOADING": "",
  "REVENGE": "ZmhLebNlcI8",
  "REWRITING": "XLGlodKH7qM",
  "RIGHT WAY, SOUL MATE": "-EG_XEDCJ_I",
  "ROAD TO THE FUTURE": "cQGTZ2WGEZE",
  "ROMANTIC SHAKER": "RKrzP8pGSRw",
  "ROUTE77": "oU367Yys1PM",
  "RULE～牙ヲ穿テヨ～": "u4pEuS1Ktmk",
  "Radiance of Heart": "NC4bvgr0fiA",
  "Radiant Letter": "a1VYxqvJ0lE",
  "Radio Happy": "9pY9MrjeLD4,3svO0tIBWmM",
  "Rainy Memories": "AChcBokBOuU",
  "Raise the FLAG": "TkiLYE91zG8,cYOCpBy6oWI,XwhljxylR_4",
  "Rat A Tat!!!": "geYG2wPPoO0,JZnwFOeTX5M,Iji4ODkdvXU",
  "ReTale": "LuXc97DJW-A,cAg-AgW8i0k,YvJlTUT9lg0",
  "Real Mind Shakes": "EhIWPMliBlc,czQGkBy5NBY",
  "Reason!!": "HUfx5nCtz1U",
  "Rebellion": "jOyiEmf7khI,AbiA1OaVZGg,7SBrmRXrCMo",
  "Rebellion (Tanchiky Remix)": "AbiA1OaVZGg",
  "Reflection": "182hHN3jWtg",
  "Reflection BREAKERS": "dXEBPXTMInE",
  "Reflective illumination night": "aaQ_KL9qK5Q",
  "Reset": "8B0mvRYH_mg",
  "Resolution": "OKZTU-HCTPo",
  "Resonance⁺": "E4V3kHTmm7E",
  "Resonate Blessing": "497deGMeeFg",
  "Reversed Masquerade": "fNIfJq_kdqI",
  "Revive": "",
  "Reward Sweets": "",
  "Ride on Beat": "MYyPW9CvvBU,gHUqif3Y4aw",
  "Ring Ring Ringの魔法": "rr0vjTlEZnQ",
  "Rockin’ Emotion": "kMZ9Ha4B4Ik,MGnLWrlb188",
  "Romantic Now": "u_V_hC7B7QA,I8di2TawWKE,jEbVHh2qnN8",
  "Romantic Now ～For Uzuki rearrange MIX～": "",
  "S!T!A!R!ting": "",
  "S(mile)ING!": "aQr0szotP_Y",
  "S(mile)ING! ～For Rin rearrange MIX～": "viOUgVWpKT8",
  "SASH OF SMILE": "fW0SnQ8YChk",
  "SCOREBOOK Memories": "l8VbCkhhQR4",
  "SEARCH RIGHT": "NW5qcYRQieo",
  "SEASON IN THE FIVE": "wbKds3J3rMU",
  "SECOND LIVINGROOM": "lmq9q6cHqf4,tZuyziAil8U",
  "SESSION!": "R5dhajcBOPU,r-vLbZyvJVs,GfbhubAjIn0",
  "SHADOWLESS": "",
  "SHIMMER": "CDugXJWxM7Y,8KEjl-jj2kY",
  "SHINING STAR★彡": "",
  "SHINY DAYS": "2buZE-Lb1Dk",
  "SHOOTING STAR": "w4jCJ1jDFwE",
  "SING MY SONG": "MVVVZTbwkZI,zqm1uxlINbw",
  "SMOKY FRUITS": "KPhurdQ9QCk",
  "SMOKY THRILL": "KRpdOd72ltw,mu5T9nQN2qw",
  "SNOW FLAKES MEMORIES": "vYJNajxnjoo",
  "SOLAR WAY": "buWcHco8vrs",
  "SOOTHING PLACE": "d33GElKFvPU",
  "SOS": "EvuXIk2Bh78,zny-LI3hUPM",
  "SPACY PARADISE": "UJn6Fk5a98k",
  "SPARKERS": "",
  "SPARKLE SIGN": "G5wpSoRfeg4",
  "SPIRIT": "Gm40yDPc04Q",
  "STANDING ALIVE": "ArkzdJspB4Q,S0PxiYYSsZw",
  "STANDING ALIVE (Nor Remix)": "UMC0YR8yo1M",
  "STAR": "BfY364l26PY",
  "STAR over STAR": "UnT9YJJ0FTM",
  "STARLIGHT CELEBRATE!": "HbnVeGzBTyg",
  "STARRY PLACE": "rMgvrDhK2qk",
  "START!!": "ZL39Sy3jiQo",
  "STAY TUNED ORBIT": "fPx8hIWpLuw",
  "STEREOPHONIC ISOTONIC": "hVOSbW2Lo3o,nu2aXcKhQOY,921GfvjCrn4",
  "STEREOPHONIC ISOTONIC (nyankobrq Remix)": "w1GaiOaIYeo",
  "STORY": "Vjbg-i3M52M",
  "STYLISH QUEEN★": "",
  "SUGAR FLAVOR": "",
  "SUN♡FLOWER": "zlz-eR0GrUg",
  "SUPER DUPER DREAMER": "KVQR6PZZhrc",
  "SUPER KICK & RAP": "HbiTJfPvnIk",
  "SUPER SIZE LOVE!!": "JCGT7KDErCI,vuBrAqY0vN8,La-fRvgU5ow",
  "SUPER SIZE LOVE!! (YUC'e Remix)": "kyucC2HXTAI",
  "SUPERLOVE☆": "Hz2qXmm2CxU",
  "SUPERNOVA": "FOmV7dBE_hQ",
  "SUPERSTAR": "",
  "SUPREMACY": "9GELzbI-8F4,9EzxaphSoZU",
  "SUPREME STARS !!!": "qETLgLTGqxg",
  "SWEET MEMORIES": "lLzUdSOa8M8",
  "SWEETEST BITE": "KIiO7rGnW6I",
  "SWEET♡STEP": "tM7nSiph-fM",
  "SWITCH ON": "",
  "Sail→Light→Sail": "QejLs57K3AI",
  "Sanctuary World": "Xu7f48O5vY8",
  "Scarlet Rose": "b-HgOofZE1Y",
  "Secret Daybreak": "Z8E9s4NIOTs",
  "Secret Daybreak -石濱翔 Remix-": "3RvdgwfyLzE",
  "Secret Light": "x_eamZw7Pvs",
  "Secret Mirage": "-04uAXHn5eI",
  "Secret Ornament": "8eThIbWuDQs",
  "Secret utopIA": "jBejinb3WUI",
  "Secret! Playful! Drive!": "KQtCM_4gq6g",
  "Sentimental Venus": "3qgBG449-i4,sc61TVMYuEk,OHNwwmKsTY0,uGhTq4NNFVU",
  "Sentimental Venus (TeddyLoid Remix)": "uxfs5ovkldE",
  "Shamrock Vivace": "7mWXV6gP4LM,_lK7ZoU-Ga4,YhPV-YewYCo",
  "Shangri-La": "",
  "Shine In The Sky☆": "7hOZPtgp6_A,IDBj6RUHDRA,gxKf4BHMWk4,oi3cUBLkVN8",
  "Shine My Way": "znFtAnTcKfo,VH5qSLoOvNI",
  "Shine!!": "-rKS3acTJ3Y,0AKHxLeyTwU",
  "Shinobi 4.0 忍者のすゝめ": "25ddtxUFVrw",
  "Shiny Stories": "dMgQeEIcV3g,CMqaWKd3IFI",
  "Shooting Stars": "o6w-4JjAxLY,wOrzuVafaa4,HNtImorm5MQ",
  "Shooting Stars (BEATNINE Remix)": "wOrzuVafaa4",
  "Shooting!!!": "",
  "Shower of light": "8tdDQ-og6Ck,S0V7FzgzBqQ,rG_LKd8gLco",
  "Sign of Hope": "G7DE6I_PZdI",
  "Silent Joker": "KaDMw8VGx8c,p3z5dWS-Crc,RJYwr7vFoeM",
  "Sing a Wing Song": "BdDOw5bJI6A,t5Kj6nsPsX4",
  "Sing the Prologue♪": "ZyZOCUIi7PE",
  "Singing Explorers": "NbKFCO95DQ0",
  "Sister": "ng3pMaeHBDk,rPp6NQYr7zU",
  "Sky Survive": "0n0ErxbtO5U,ctZVHZv984k",
  "Slapp Happy!!!": "",
  "Sleepless Nights": "NDL9tpUteBI,2Dmjx6f47oU",
  "Smile Smile Smile": "",
  "Smiles In Wonderland!": "u58n6q7dJ7k",
  "Smiling Crescent": "8yczNOxFnFY,EH6br1oX4mU",
  "Smiling Platter!": "JdYNaVB-tUA",
  "Snow White": "EOzZCZ9Gj-o,ZabUWkDpe9I",
  "Snow White（DÉ DÉ MOUSE Remix）": "-afZAS0Citg",
  "Snow Wings": "JVSId71FeQ0,A-TAIeClhbc",
  "Snowdome": "",
  "Snowflake": "ln4Zkas5LAU",
  "Snow＊Love": "APDP5VwAd-Q",
  "Sparkle": "xw1Pvd5bsjU",
  "Sparkling Girl": "J8ucwaObVFE",
  "Special Wonderful Smile": "boXz49v6Krg,zfZ7ul2OGY4",
  "Spread the Wings!!": "IllFL-bksH8,Ral6WOgSO6k,BvmOJR3RYXM,eRhtM4roYs0",
  "Spring Screaming": "Pn9XzgTBRaw",
  "Squall": "",
  "Stage Bye Stage": "6chPV6rUmIE,NMIEAhH_fTU,oDQGj49oGgE",
  "Stage Bye Stage -emon(Tes.) Remix-": "HauaXUaeRmo",
  "Star Impression": "zdh78qi40Uc,WUjK_7ac3gM",
  "Star!!": "aZipKaHr994,VZiP2XbI0sk",
  "Star-mine": "BLkCR5h_Sv4,vvBP7JKeqYc,TdEpC2-2m9E,SdNam7hLMjY",
  "Starry Melody": "NoVqHS5pfDI,soQU9fSpTC8,NS_Ouw1e9Bk",
  "Starry Night": "4hjN5TWrEC8",
  "Starry-Go-Round": "FeQeTpzEm7M,jA5u14zsCcc",
  "Start up Stand up": "t0-ODmpSE7k",
  "Stellar Light": "1ekj1pUHjnk",
  "Stellar Stellar": "UmyCyqUpcxY,QMoMOV9NHJA",
  "Stick to my weapon": "vVBebCVCZ1I",
  "Still Love": "",
  "Stillness≒Movement": "vmj6ZDTXL-I",
  "Stories": "652VIAyhGxM",
  "Strawberry pain": "FEAp_vt5CqA",
  "String of Fate": "Fp4r6fZi__E",
  "Study Equal Magic!": "8WcS3L_JamM",
  "Sugaring Off Party!": "KOwZa0V_Rq0",
  "Summer Night Paradise": "W2hGvljzE9A",
  "Sun! High! Gold!": "IDTl2YlCpEg",
  "SunRiser": "tCrrg2lcDsM,VDLbzmmyyNo",
  "Sunny Day Sunday": "",
  "Sunny day, Perfect day": "uWHqtgroJJQ",
  "Sunrise Dreamer": "",
  "Sunset★Colors": "a5L0UPF07c0",
  "Sunshine See May": "TAOiUuyO7Ho,FVYthK7830k",
  "Super Duper": "FuQMRwEmPH4,KdjIIPVoj9k",
  "Super Funky Piece!!": "d9BVd-CtYdc,ZzQ4V78MSG4",
  "Super Lover": "XwJf90xtqn4,QEzKcLnUhh4,v6jlhssTJNA",
  "Super Lover（Hylen Remix)": "t_tedGQuKQs",
  "Superlative": "Ie_btWuTW6M",
  "Supersonic Booster!": "Yo4mLd1efcE,fQcjDJq4sOU",
  "Swallowtail Butterfly ～あいのうた～": "",
  "Sweep Your Gloom": "Z94fi4Jc4ck",
  "Sweet Diamant": "E6W2e7yQ59A",
  "Sweet Magic": "KObbQEtDg_M",
  "Sweet Memories": "f4vZtYqzXvc",
  "Sweet Sweet Soul": "MQpYWtDPtmE,miy789T6w9c",
  "Sweet Witches' Night 〜6人目はだぁれ〜": "fEg6OogHwc4",
  "Swing Your Leaves": "Fti-_m2jY3g",
  "Swing it!": "4vFn5zb7Nzk",
  "Symphonic Brave": "PX9v7XvwOlA",
  "TAKAMARI☆CLIMAXXX!!!!!": "gBvq0uP4Hos",
  "TAKU INOUE SELECTION!!!! feat. DJ KOO!!": "",
  "THE FIRST STAR": "RmuHLeEN1YM",
  "THE IDOLM@STER": "AUsfymKaKMA,vWIFtpevy8k",
  "THE IDOLM@STER 初星-mix": "p83-nj9HLWs,n-nrfqU1w2A",
  "THE LAST PRIDE": "XiH8Bn7zNFo,VDnxOtz1chc",
  "THE VILLAIN'S NIGHT": "n4MCOhnFOrs",
  "THE 愛": "",
  "THIS IS IT!": "8ZTX4GoYC54",
  "TODAY with ME": "",
  "TOKIMEKIエスカレート": "hIr5__nVaWo",
  "TOKIMEKIエスカレート -Tropical Summer Nude Remix-": "pRDpVJ8z5RE",
  "TOMORROW": "",
  "TOMORROW DIAMOND": "AYrIjBXqZWY",
  "TRF×CG -DJ KOO Mix-": "",
  "TRI-ANGLE DRIVE": "Ws8d-FkVThc",
  "TRIAL DANCE": "vt1bI0nJU_U",
  "TRUE COLORS": "_-AR53Z3tXM,A70V2RuCumE",
  "Take a StuMp!": "-deBUIgOCkU",
  "Take me☆Take you": "jC29YAtZn4U",
  "Take!3. 2. 1. → S・P・A・C・E↑↑": "ucLXlWTPxys,8Lw5rScLXxM",
  "Tame-Lie-One-Step": "O0Ylv6GNWMQ,f1Ykuu5O5vc,bBEiYO6Td5A,tW_Em8uObwA",
  "Teatime Cliché": "URRmSi0awFc",
  "Teeenage☆Groovin'": "v3HAPSihRUw,bbXTERRPV9Q",
  "Texting you": "5HfzSnvLGuU",
  "Thank You!": "k_VC-P1AioE,H4H6mqjsx9k,Kuei6no4E6U",
  "Thank You! (Giga Remix)": "rSsduq5DOn8",
  "Thank You! (Snail's House Remix)": "rSsduq5DOn8",
  "Thank You! (TeddyLoid Remix)": "rSsduq5DOn8",
  "Thank You! (y0c1e Remix)": "rSsduq5DOn8",
  "Thank You! -MR Remix-": "tyXP1knryPQ,aoa84oTM_JQ",
  "Thank You!（☆Taku Takahashi Remix）": "rSsduq5DOn8",
  "Thank You!（チバニャン Remix）": "rSsduq5DOn8",
  "The 1st Movement～未来のための二重奏～": "UDE0Mz3lJQA",
  "The Radical JOKER": "izdlie_36Uc",
  "The Rolling Riceball": "FL-NhmFGQYw,SmYiRx258Do,vjakZvd0feU,568aZaWSTbk",
  "The Rolling Riceball (LindaAI-CUE Remix)": "",
  "The Symphonic Daylight": "k2ResmOS8aY",
  "The cute!!!": "nSo5Eqarg6M,bP2wxVmsEDs",
  "The world is all one !!": "ccZ8Ck2T58s,HT5QGouEa-E",
  "Tick Tack Voice": "bh-MaHgk37w",
  "Time Before Time": "4LD5Ds5Vc9s",
  "Timeless Shooting Star": "ncridR7PQOM,qApldtgM_QQ",
  "Tip Taps Tip": "",
  "To my darling…": "JV54VRr1XTY",
  "To...": "7I0r3vY2F4Q,cl6ai0dke5w",
  "ToP!!!!!!!!!!!!!": "ZWBJpno17Kk,GpGpdp4rTKo",
  "Tokyo自由系*ガール": "bbwspfN-B28",
  "Tomorrow Gazer": "s14pxhlqEnc",
  "Tomorrow Program": "3lc2PAJGwf4,PDDXTAaN4W4,spgKt_1djsw",
  "Tone's Destiny": "2iVTYydcy8E",
  "Top Secret": "J8fGYM03jsU,4qMAHOVPWdA",
  "Toward Pole Star": "wFciRpuZLfg",
  "Tower of Adventure": "",
  "Tracing Defender": "Jgqhkdim1-s,AAcw716Wd3w",
  "Trancing Pulse": "QwuEEA1jSCQ",
  "Transcending The World": "tZBGg95hMoM",
  "Traveler": "",
  "Treasure☆": "ltxfIfGYCVw",
  "Tricolor Rendezvous": "ojwu9vTCNoY",
  "Trinity Field": "kV_XgNUdULA",
  "True Horizon": "pKsbukOsdNM",
  "Trust me": "Zx8F8OLsDSw",
  "Trust me now": "ogJuYypzl2w",
  "Try it now": "mm_Pq1uvzjc,X59st5FuS5I",
  "Tulip": "FFamILNw9v4,qJ-TCAK3pWk,m1NDwImzDrE",
  "Tulip -TAKU INOUE Remix-": "IA5qOhkcr8U",
  "Twilight Sky": "LmFRV77mZRM,M4Gs5hQEA6E",
  "Twilight Sky -烏屋茶房 Remix-": "iZZuAXfU1Rc",
  "Twilight Sky ～For Rika rearranged MIX～": "",
  "Twinkle way": "EE0eNJhtGoA,SdY0kWK1RPg",
  "Twin☆くるっ★テール": "1RC8AzpLNhM",
  "ULTIMATE FLAME": "Hu95ZiJtWhw",
  "UNION!!": "KrdfHPbbx_c,cxtxp2FXh-U,DxxGWKtUjLY,m6yypueuSfc,mXnK4imFDT0",
  "UNIQU3 VOICES!!!": "zpXqZBSjrSc,m5OhcXo32jk,qc4zEWeAXQw",
  "UNIQU3 VOICES!!! -山本真央樹 Remix-": "qc4zEWeAXQw",
  "URGENT!!!": "",
  "Understand? Understand!": "aIOAnSojfRw,YyjqRMuSNIg,260z2Pp3ajY",
  "Undiscovered WORLD": "JvYbTx-x91w",
  "Unhappy Light": "t5-yEjei1MM",
  "Unknown Boxの開き方": "vb1bmqAVxYQ,H7AfzilyASo",
  "Unlock Starbeat": "-9_Lkik9ltA,3MP3v2t9m6I",
  "Unsung Heroes": "QHXycqagUXY",
  "Up!10sion♪Pleeeeeeeease!（Getty Remix)": "",
  "Up!10sion♪Pleeeeeeeeease!": "WZCKPCGkRjI,N8enKxcf_6k,N4QJMn16HU4",
  "Upper Dog": "ihg0WTuH18I",
  "U・N・M・E・I ライブ": "yqI-InlItm4,lLObvK-OsBc",
  "U・N・M・E・I ライブ -MR remix-": "ZN5jqFl2KZI",
  "VACATION": "",
  "VEIL": "AbxzlgJTM-I",
  "VELVET QUIET": "gBw4q4ClJpc",
  "VERY BERRY LOVE": "OvxsVStUoaE,Gk-NiBl1rNI",
  "VICTORY BELIEVER": "r8cDOwwqI5M",
  "VIVA!!ファミリーリズム": "WbUBNECDhis",
  "VIVA☆アクアリズム": "kP6H5omw8os,O89TLxQNWHM",
  "VIVID イマジネーション": "0svhMrNeOJ4,eSz9k0xs6Kw,huK3Nlz_T0k",
  "VIVID イマジネーション (TeddyLoid Remix)": "eSz9k0xs6Kw",
  "VOY@GER": "HJKqSYK_z0w,KepPQ8pYr74,w_6ntHIQ3ZA,JGu028T4irw,dYk0C6Y4UA8",
  "Vacation VS Summer ～ナツとヤスミのアンビバレント！～": "EzaXcR3lS70,6JiosI_1jeA",
  "Vast world": "xJam2D9j5J4",
  "Vault that borderline!": "MKwFG2VjhQE",
  "Vertex Meister": "dGQi0FDLTWA",
  "Virgin Load": "",
  "Virgin Love": "KsCFCkijI08",
  "Vivamente!": "d5kZSkoGni4",
  "Voyage": "wtbpifZUt_g",
  "WE ARE ONE!!": "wVd3hAJAgSo,ARdwTFyX1tU,Ex4EvDngwwE",
  "WEDDING BELL": "",
  "WET": "Pc2DErxioKM",
  "WHITE BREATH": "YK75Zu6Y9HM,qMNo5emx7yQ",
  "WHY?": "9ZJHSsW0gOc,Roal0b3gs90,iqjGWOmFVik",
  "WHY? (nyankobrq Remix)": "TnUOmjySmwc",
  "WINTER COMES AROUND": "",
  "WINTER and WINDOW": "X5r65SfYD-M,0Y-Lm7G90PU,7eCiM-StI8A",
  "WORLD WIDE DANCE!!!": "oS9-vWGgtNo,_PoYvVeYcq8,b8Qhgef4-G8",
  "WORLD WIDE DANCE!!! (KiWi Remix)": "_PoYvVeYcq8",
  "WOW! I NEED!! ～シンギングモンキー 歌唱拳～": "iEWuG4R-6G4,o5xAAcVP0y8,f5PoFiLXGcQ",
  "WOW! I NEED!! ～シンギングモンキー歌唱拳～ (TORIENA Remix)": "Mm_WFVpbgLw",
  "Wake up!!": "X56QfFhKXEU,agmdfTGxnDg",
  "Walking on the Square": "Dl0wS1Bpy5E,lxInJHgnKXM",
  "Wandering Dream Chaser": "Kfkk-UWTByA,37n3c4MVLLw,qEVxVHtN-SA,Q7RNyiizmDI,fZkadm6MWic",
  "Watchword": "mBPFWHe7Vbg",
  "Waving FLAGS": "5Cwe9__6Ajo",
  "We Have A Dream": "",
  "We can go now!": "mvGa1ddYit8,nTkMCLcRb1g",
  "We just started": "f7lv3lw8Y9w",
  "We wish your smile": "0ZFH7lET48A",
  "We'll find a way": "oKkhx8YLMSQ",
  "We're the one": "7gNUSP46azY",
  "Welcome to Japan!": "YHgJlyy6JFg",
  "Welcome!!": "r7deikRdEho,Z6bet-s6NTc",
  "Welcome!! (Giga REMIX)": "4vNQv8-2US8",
  "Welcome!! (Snail's House Remix)": "4vNQv8-2US8",
  "Welcome!! (TeddyLoid & tofubeats Remix)": "4vNQv8-2US8",
  "Welcome!! (チバニャン Remix)": "4vNQv8-2US8",
  "Welcome!! -MR remix-": "4vNQv8-2US8",
  "Welcome!!（y0c1e Remix）": "4vNQv8-2US8",
  "We’re the friends!": "DAjyvEacexM",
  "White Night! White Wish!": "MXWTuX-QC00,ISoaL8q9TgI",
  "White Story": "U1f3ay0j8yo",
  "White Vows": "WsS5bxdOtiU,TAwRWcnNooQ,l9kAK87HVAo",
  "White again": "60BTVDBkt8Q",
  "Wildest Flower": "iiiLtE4w2pE,AIKmggz0BeI",
  "Wish you Happiness!!": "mDQ1S7g5UrQ,oEWhZYZ83NQ",
  "With Love": "KAaRxWTR91o",
  "With you": "s5-6ICR5kAE",
  "With…STORY": "CUJL1mP6aTQ",
  "Wonder Scale": "NkC8ahzYm3k,GHPFRBuAPzM,wEe9wmjZ4ek,eD3jimowimI",
  "Wonder goes on!!": "mKSQzO_ExDQ",
  "Wonderlander's Party": "ojpde-ShjAE",
  "World Changer": "BOqhPqUT00U,b2iDl47mMso,195ZksGfYsE",
  "YATTA!": "tGVt8VniMkg",
  "YELL OF DELIGHT": "ldQmIRzpZA0",
  "YELL～エール～": "",
  "YES♪": "POwnwMDgZMY",
  "YOU往MY進！": "7yJbCqiHFbU",
  "Yeah！めっちゃホリディ": "",
  "Yell Song": "E3172YGzrWE",
  "Yellow Big Bang!": "CSWoZ9Q61eQ,aL7xXuf7g1w",
  "Yellow Big Bang! (cosMo＠暴走P Remix)": "",
  "Yellow Yellow Happy": "",
  "Yes! Party Time!!": "Otr-DgB64JQ,SGhOje68GFU,v5D6bHe8Xfg,x9b-DXltOc4",
  "Yes! Party Time!! -Massive New Krew Remix-": "pEdG9GFztQ4",
  "You're My Only Shinin' Star": "",
  "You're stars shine on me": "lVmdvliyuAw",
  "You're stars shine on me ～For Miku rearranged MIX～": "",
  "Your Nobility": "w46oNJE9mi8",
  "ZETTAI × BREAK!! トゥインクルリズム": "BZbmbITB54M,9lYzzOQGuyk,jK6GOqYAyOA",
  "ZeroGravity": "rf2A3VTRdt0,-J3OnxCEzl0",
  "abyss of conflict": "4IuT3jRDYpA,BeSsPrA2BA4",
  "addicted": "Nd5WTNKvi_o,FzJ79M2SrgY,yoqX17Q7CLk",
  "addicted (Snail's House Remix)": "FzJ79M2SrgY",
  "always": "UPpjEKhG3R8,sZNnZxPZ9sQ",
  "ambiguous": "xtVE4qGVWOA",
  "ambivalent world": "",
  "arcadia": "VT0jwrJQkTo",
  "bitter sweet": "YMJYztCuazI,d-X5D33NcVw,3sfmGUoPOgY",
  "bitter sweet (チバニャン Remix)": "L9i--EawK0k",
  "brave HARMONY": "tKFLvBtBBTM,K65meAo6u1A,scyh94o7k8g",
  "brave heart": "E7ga8ca3Lgc",
  "catch my feeling": "Cf2vFZZpGbg,e_6wyfAO_fw",
  "cherry＊merry＊cherry": "6jeZ1yqM508",
  "choco fondue": "",
  "clumsy trick": "ND5MsmApfTE,jFTVJQjsZrc,zsIi7tUNemQ,P7Dg1RPe8uA",
  "comic cosmic": "9qJJCiqIQZk",
  "continue": "",
  "dans l'obscurité": "RKNwzeUwRv8,mrcAkOIrORo,WCW3-Y8rkz8",
  "dear...": "3X_cyIxxGxo,cYvWB35lqU4,cPgK2CB4cqc,jBL7u8vXrZM",
  "dear... (TeddyLoid Remix)": "cYvWB35lqU4",
  "destiny": "XDSPECaTAUE",
  "edeN": "YQh3fkmolAY,kFkZG6qYZS0",
  "fruity love": "qrhRBFkye5k,DGuwZE6CiVE,EBqgYPo8_GU",
  "i": "B0rtKaDDnj4",
  "if": "IIrIA-nJTDM",
  "ilLUmiNAte!": "unztAJiwbNo,lxrIX-Yq0HE",
  "in WonderRadio": "3cAuHbgPXuA",
  "in fact": "gqO5THv6eYU,G-kQNi3WAvg,nRPdb6qQxec",
  "inferno": "UNRqhgKWuXM",
  "inferno SQUARING": "i_RMGJYjucY",
  "it's me": "RM2NXD7OFP4,_XE0oq0M9Yk",
  "lilac time": "KOuBVeyHdoQ,moCfzviCtHQ",
  "lilac time ピクニックライブ・アコースティックVer": "",
  "little trip around the world": "9eheH54L7S4,07I9PzC_geg,mPuW9fyOFRY",
  "livE": "VHDc49VU-8w",
  "marble heart": "OWHUM1z8_-U,jxFxLIl4HFM",
  "mellow mellow": "uZKafsDadEg,dybEycyJ4ZI",
  "mermaid fermata": "WAToXl3qSLY",
  "motto☆派手にね！": "",
  "my song": "jZLo2W5iv1I",
  "my sweet heart": "WjfU3lUyH6M",
  "piece of cake": "wLM5zHXA-ZM,w7FkAeWh1S8",
  "pinkのfebruary": "",
  "precious love": "GHEmRDRsNsQ",
  "relations": "moXG1ZwqYew,T__zXBdwY9k",
  "rise": "",
  "shabon song": "I-GQgJNC-o4",
  "shabon song ～For SS3A rearrange Mix～": "VYIK6843f-U",
  "shiny smile": "9FC2yasgUgE,YCBXQS7Wbiw,yJExWld6MQo",
  "shy→shining": "1UATejL6cJM",
  "smiley days": "KUP8B-jcKPI,mbyBtTn5IdA",
  "smiley days (TeddyLoid Remix)": "KUP8B-jcKPI",
  "staple stable": "",
  "statice": "MILfo2y-Aa8",
  "sugar sweet nightmare": "",
  "sunshine": "",
  "survival dAnce ～NO NO CRY MORE～": "5sO0knVrpJU",
  "tear": "iC9kL21RAJY",
  "to you for me": "WT7UH3hIDkY,ESSFUT6lRLo",
  "vivid color": "uAq8QPGgwng,aFBJG7uAbb0,Zo_4-eis_6s",
  "vivid color (yukiyanagi Remix)": "aFBJG7uAbb0",
  "vs.BELIEVERS": "NCVuBD-IjIo",
  "you're": "TmETi05aX0Q",
  "zone of fortune": "",
  "À La Carte FREEDOM♪": "abcWq0ZKF9w",
  "ØωØver!!": "MJ7XAx8LWJo",
  "ØωØver!! -Heart Beat Version-": "-y_FQ_DFl1I",
  "“W”onderful Tactics!": "P1GlBWnYy_w",
  "“W”orldwide Ambitions!": "3BiYlu0U0ng",
  "“Your” HOME TOWN": "pS4VahfOIN0,7VK291Ztpmw",
  "…掲げよう、偽りなき自分を。": "pFva87pGRJw",
  "∀NSWER": "_IDD8uwFhCo",
  "∀NSWER -AJURIKA Remix-": "_IDD8uwFhCo",
  "∀NSWER ～ののの物語～": "200ZK9OCC-w",
  "√EVOLUTION": "lBA9iR8ccCc",
  "∞Possibilities": "eWLlDvqZikA",
  "♡Cupids!": "i_gG2voeiYU",
  "♡桃色片想い♡": "Jisgoq46zQE",
  "♪": "Jisgoq46zQE",
  "「また明日」の約束を": "UCGiwZaj390",
  "あいくるしい": "AXvWrBoXbtg",
  "あいくるしい ～For SS3A rearrange Mix～": "69rwrhi5ZwQ",
  "あおぞらサイダー": "nuKYhJ5SVHw,9b4V6Xosy_U",
  "あこがれステッチ": "lgLylPa6UTw,qEz51Ifi9v4,imO9zW6JUB8,3f0j6XVc3tY",
  "あしたアイシテル": "",
  "あたしを彼女にしたいなら": "-n67mh7qFNc",
  "あたためますか？": "ka03Qh1t9kQ,KqJ71WrlVJY",
  "あったかな雪": "47hu5auJDpA",
  "あっちこっちプリンセス": "VxLSzERfxe4",
  "あなたは幸せになる": "K-FpqbYrCcg",
  "あのね、聞いてほしいことがあるんだ": "hqMyKeGCJDk,c-aQlkOJ3dU,Ixy6OqmQPGc",
  "あのね、聞いてほしいことがあるんだ（DÉ DÉ MOUSE Remix）": "c-aQlkOJ3dU",
  "あの子が街に来なサンタ": "avhQWrXvL7A,VMt9K0aFOuo,Mca_mdMHOWs",
  "あの日のナミダ": "",
  "あの花のように": "NaCSpXECH2o",
  "あめにうたおう♪": "xPKMzPYnC1Q,KabTHBernx8,ieet5gJyhDU",
  "あらかねの器": "Cp4Qr4nb75A,ZXN8_JQIhIU",
  "ありがとう…": "",
  "ありったけの輝きで": "nULa5_h_IOY,WMkSD5-lm6Q",
  "あんきら！？狂騒曲": "llNaiTG5Uh0",
  "あんずのうた": "dtdsNiebbs4,5MuaJDv9FoE",
  "あんずのうた -ノるあんず2000 (DJ過重労働) Remix-": "",
  "あんずのうた ～For Kirari rearranged MIX～": "",
  "あ・り・が・と・YESTERDAYS": "",
  "あ～よかった": "",
  "いっしょ": "FMpR24DmjXw",
  "いっぱいいっぱい": "Yydu86OiwSQ,jshPiR_R2yc",
  "いつか Shiny Days": "QgFZr2kST6U",
  "いつかこの瞬間に名前をつけるなら": "jSA6wmtXaq4",
  "いつかの、いくつかのきみとのせかい": "9drSbdIDs-s",
  "いつかのキミへ": "y2VturCh4PI",
  "いつかのトライアングル": "u0f0qvISVfc",
  "いつだって僕らは": "NAWIdRaCIzs,sgq2T14EyMo",
  "いとしーさー♥": "-pPzdP1DexY",
  "いとをかし！～一彩×合彩～": "FN_3Htu9h5k",
  "うぇるかむ・はぴきらパーク！": "jdJ2V2_Nc9o",
  "うまぴょい伝説": "tAtRkJHGbfk",
  "うれし・あやかし道中記": "",
  "う・ふ・ふ・ふ": "",
  "おかしな国のおかし屋さん": "fqWpvCmQNSY",
  "おとなのはじまり": "Ovi7IrprOCo,i1BYVt-bd3w",
  "おねえちゃんデスコ": "_OubH11Zcf8",
  "おねだり Shall We〜?": "j30Zvyz35i8",
  "おねだり Shall We～? ～For Kanako rearrange MIX～": "",
  "おはよう！！朝ご飯": "7T549Oodh1g",
  "おまじない": "4nFvotoAfxs,QtKJ1W3R2Z8,TfY87DKs7kQ",
  "おまじない (picco Remix)": "",
  "おめざめめーめー": "-YKzK4aq6PU,rMRrfffj_Mg,WwrBRLw-kNk",
  "おもいでのはじまり": "",
  "おんなの道は星の道": "MloDUHrdzXU,viVUwc8d_jU",
  "お散歩カメラ": "-jKeANPojYY",
  "お願い！シンデレラ": "MzliA1YpVEQ,5jFxZsMs9Fc,V-djx49M86Y,7cCKVa_eInQ,hB0Wc2a8ckY,qbpTl11qk9A",
  "お願い！シンデレラ - しんげきRemix -": "4xtl48QJ8dw",
  "お願い！シンデレラ -JAZZ Rearrange MIX-": "sMRWcdKKHIE",
  "お願い！シンデレラ -山本真央樹 Remix-": "4xtl48QJ8dw",
  "お願い！シンデレラ ～ゴージャス・トロピカル Ver.～": "06v0S7blKxQ",
  "かざぐるま": "",
  "かざぐるま～Windy Road～": "xz1lPd6Qdms",
  "かたちあるもの": "",
  "かちドキ": "nKs36yaeLfo,T6X2MREymGM",
  "かぼちゃ姫": "hTN7-8Rxsn0,KWBQJx9rjFE",
  "からふる・とれじゃ～わ～るど！": "6z5lPQE9L7k",
  "がおちゅー♪さふぁりぱーく！": "SfimWSNhREc,w7o93Y5CvXE",
  "がむしゃらに行こう！": "2ZAncawGd1o",
  "きっと": "Z3QHA7wosQk",
  "きのこの唄": "",
  "きまぐれユモレスク": "fChDvm1BC8s,PkwEF5_mShI",
  "きみがくれた言葉があるから": "47nLIv4WI6w,OhM5kWgVlU4",
  "きみにいっぱい☆": "8R9k_USo1_0",
  "きみにとどけ": "LwlEPr6m2ZY",
  "きみの一等星": "Jaoi92udUS8",
  "きゅんっ！ヴァンパイアガール": "QrpWGVAjXvM,GUFLZXDenzQ",
  "きゅん・きゅん・まっくす": "QkO1DC96kIM",
  "きよしこの夜": "",
  "きらりんロボのテーマ": "MSC0-x_wu0w",
  "き・ま・ぐ・れ☆Café au lait!": "bLY5EsDn4fM,JDv0vWY4YwM",
  "くだらないや": "2DzVDQvigqM,da_EfySz26c",
  "こいかぜ": "3CCTVpp4qP8",
  "こいかぜ -Night Wind Remix-": "_JrYHdpeS1w",
  "こいかぜ －序章－": "_JrYHdpeS1w",
  "こいかぜ －紺碧－": "_JrYHdpeS1w",
  "こいかぜ －花葉－": "_JrYHdpeS1w",
  "ここにしか咲かない花": "azdMCStWK8M",
  "この恋の解を答えなさい": "nX0W-gXRPwM,Yytq8H5vTdI,62uEQQ253vs",
  "この空の下": "mp_jAOXZ4f8",
  "さあ舞い上がれ": "9AWm3InRYkU",
  "さいきっく☆うぉんちゅー！": "W2RvaI45zg4",
  "さかしまの言葉": "6_3-25w6e8A,d-OUdMB2szA,UrH8UW1WYNQ",
  "ささのはに、うたかたに。": "3r8SLmVdQTc",
  "さやけき花の生命に": "kfCSwmoZSTc",
  "さよならをありがとう": "",
  "さよならアロハ": "BRHRbFolwK4",
  "さよならアンドロメダ": "3g1-u8qPxkU",
  "さんぶんのいち": "DU1JiGEun8g",
  "さんぽ": "",
  "しあわせのレシピ": "",
  "しあわせエンドロール": "-3Qvx-OpGj0,v8T8Qj-1x-M",
  "しっくりとゆっくりと": "",
  "しっぽのきもち": "",
  "しゅがーはぁと☆レボリューション": "ke1rtB94s2U,U2szkiLwh6k",
  "じゅもんをあげるよ": "",
  "じょいふる": "ETL1Tb40hvU",
  "すいみん不足": "",
  "すてきなホリデイ": "",
  "ずるじゃん": "jxrEVf0QvqI",
  "せぷてんばぁ": "",
  "ぜんぜんあいたい": "",
  "そしてぼくらは旅にでる": "_DLGQS8Tu5o",
  "そだてっ！たいむかぷせる": "RqeNfOKeSu4",
  "そのままで": "TTnRKAKwdaM",
  "その場所へ行くために―KEEP ON FIGHTING―": "IPF0Ka0FEnA",
  "それが、愛でしょう": "",
  "たいせつなひと": "",
  "たいせつなもの": "i5w7kpe9aCw",
  "たくさん！": "Klwm1aOMQaY",
  "たしかな足跡": "CDJRhawL4gw,YQZJr4eUh-I",
  "たんけんぼうけん☆ハイホー隊": "PZsdSxSIkkM,WjjpKENH-ZA",
  "だいぶ・いんとぅ・にゅ～・わあるど！": "posa8vfWp54",
  "だから今夜きみと": "",
  "だってあなたはプリンセス": "K8VduNfgB1Y,gXi7jV7D8tQ,7oYRc9k4P5w",
  "ちいさな恋の足音": "irwponQgXgU,7O8Z0KmaeJ0,61AT62up-vs",
  "ちいさな恋の足音（DÉ DÉ MOUSERemix）": "7O8Z0KmaeJ0",
  "ちゅ、多様性。": "322KYzjzpoA",
  "つぼみ": "kSp6SqZ-8QY",
  "つぼみ -DJ'TEKINA//SOMETHING a.k.a ゆよゆっぺ Remix-": "5j-Ue05l5X8",
  "つよつよ最強エクササイズ": "-BhIzqm4H4o,a1cspozHmeQ",
  "てがみうた": "",
  "できたてEvo! Revo! Generation!": "9LNOBJuGqEQ",
  "でれぱ 拾年の宴": "fPV4H6u5skc",
  "でれぱDEないと": "bGxRQC3ZVts",
  "でれぱれ〜ど": "l8mBxx8rFa4",
  "でれぱ音頭": "lHlym0Xz9Ek",
  "とある英雄たちの物語": "MVyJVhs4NeQ",
  "ときどきシーソー": "6v-onwU7nDk,6CYXO22rl_0,YgsrUrs_f9M",
  "ときめきのソルフェージュ": "9tMj2ytElGo,lEe4rBYLtQU",
  "ときめきエモーション": "QulHtowM_6o,vA4SaGCdD0k",
  "とくとく…… とく……": "xgeyWmAmaJw,yyDHYwKA7JY",
  "とどけ！アイドル": "TJyEFeHKnFc,4Ktvj49h10o",
  "とどけ！アイドル - しんげきRemix-": "",
  "ともすれば、（中略）アイドル": "oy5LOGTioNk,t7RGIiMn9Po",
  "とんでいっちゃいたいの": "OyzS-ZznD3Q",
  "とんでいっちゃいたいの -北谷光浩 Remix-": "Eh0A4agiE_I",
  "どうにもとまらない": "",
  "どっきり☆ハピバ": "",
  "なつっこ音頭": "X5qJxhqJsvY,NUdBKHry5gU",
  "なみだのくに": "xXM9VKauxgY",
  "なんどでも笑おう": "58oHUJimyns,LHSu3J3ZhnI,dLOtou6FPYw,PDuzex3U9O4,Li2s_KuaRso,xHLXFlB35nE,l1bTkPrGNKU",
  "にょわにょわーるど☆": "Fd0CgEpgbTE",
  "にんぎょひめ練習中！": "ogt71McH86c,wLuBEHlNS3E,Hrt8rgkJ4SI",
  "にんげんっていいな": "F22AT91XVOA",
  "ねぇ、ねぇ、ねぇ": "0jjh4ury-Tc,-rT9ozKFQ84",
  "ねがいひとつ": "",
  "ね～え？": "",
  "はじめてのチュウ": "",
  "はっぴぃ☆ほりっく": "",
  "はなしらべ": "HEy-OynKJ0c,ImGjRmpvvCE,xjsXR4aakNs",
  "はなまる": "",
  "はにかみdays": "qMwag2jXHQQ",
  "はぴ！やば！まいまいんど！": "iTGwiQ__OUc",
  "はらぺこ泣き虫": "t8fAtUK38WA",
  "はらり、ひらり": "-0o3iSkXkMM",
  "はるかぜバトン": "4Df55tcDK1E",
  "はるのきおく": "",
  "はんどめいど・きみはーと！": "v6xNzBudPbY",
  "ぱ ぴ ぷ ぺ POP!": "DGx_WM4LQZo",
  "ひだまりの中で": "ETzQxTucf_Q",
  "ひまわりマークをさがせ！": "L96DGEax3so,mPfIZjPIg_Q,uOY6t2XEP4U,fwjYc4ZX7r4",
  "ひめくりモザイク": "TiMQmKcIBvQ",
  "ぴにゃこら太絵かき歌": "",
  "ぴんとこな～蝶よ華よ～": "4gfjorR2sOE",
  "ふたつの月": "",
  "ふたりのもじぴったん": "",
  "ふたり繋ぐ星座": "xh9fpiCGVQQ,p8u4AivQl0w",
  "ふるふるフューチャー☆": "46OHNTkCS70",
  "ふわふわ": "yS-fsWrARw8,tFk5_F7JPh4",
  "ふわもこシフォンなゆめのなか♪": "Joi63YF0lrk",
  "ふわりずむ": "F1BwsoGO_BM,MTXNPxe8v9k",
  "ぷちどるのうた": "",
  "ほっぷ・すてっぷ・ハイ、しーぷ！": "UwqYfcYEMxo",
  "ほほえみDiary": "qovwiTqWpsQ",
  "ぽっぷこーん・くろーぜっと！": "u2k1lgPTALk",
  "ましゅまろ☆キッス": "KnZEVUM96nY",
  "ましゅまろ☆キッス ～For Riina rearrange MIX～": "",
  "また、はじめよう。": "",
  "またね": "iZJIHthNU0I",
  "また君に恋してる": "0EqDT4-fGhs",
  "また明日": "QYpNus7FJPg,P7j2qGoipys",
  "まだ見ぬ明日": "uXO2CzVsOmM",
  "まっくら森の歌": "",
  "まっすぐ": "qH_IDQhHths",
  "まほうのまくら": "HeYpxnIbydc,exEjpg2vnPc,rnRts2HCi3c",
  "まほろば": "",
  "みちづれ": "vp2M8uT1Q7A",
  "みちなるひろがる": "qwfpgEhngVI,hQlqWUP5DP0",
  "みなぎれ！ボボボンバー": "4wqDL1UEnkM",
  "みんなのきもち": "977O0CVLZWQ,TMwzJ4ba0AE,jLiyCYcjZ8s,43BwBld_LJE",
  "もくろみインディアNight": "Fm4og948Qco",
  "もしも「カワイイ」が世界からなくなっても": "NGZCNRzK3rY",
  "もっふ・いんざぼっくす♪": "SqanLEccuu4",
  "もふっと・ゆにばぁ～す・とらべら～！": "6UxbJP0eSS8",
  "もふデビ★うぉんてっど": "LswBt2b4PMs",
  "もふ・きゅ～と・デイズ☆": "7r3uziJEON4",
  "もりのくにから": "Q6g9ms61jTo,0W34kqJ_2bk",
  "やさしい両手": "",
  "やさしい気持ち": "Zk1rXEfpv6U",
  "やさしさに包まれたなら": "",
  "ゆえに…なんです": "ZMEp5xFcaWg,7opKpKqh5i8",
  "ゆきゆきて華やかに": "_0ibCl5Ohs0",
  "ゆりゆららららゆるゆり大事件": "",
  "よりみちサンセット": "3-OEAy-Yqzc",
  "よりみちリトルスター": "8NsrEm_m2Oc",
  "ら♪ら♪ら♪わんだぁらんど": "",
  "らびゅらびゅ": "",
  "らんまん開花！": "eoitRSQNVcA",
  "りんごのマーチ": "DbgWQl_ofbc,NuLbZuhMVNs",
  "りんごのマーチ (COR!S Remix)": "",
  "れでぃお☆マジかる": "",
  "わかし・さわがし・スカパンク": "niYdRywrGeQ",
  "わたぐも": "Ov8iS_H2dS8",
  "わたしの一番かわいいところ": "Rug36ZGPADQ,C2ZvoS_-5JQ",
  "わたしの主人公はわたしだから！": "B8W-Zx_20E4,a1i8KSBiDzQ",
  "わたしは花、あなたは太陽": "zJAZPXvSbnM,RcD4AigDh2E,i_7Kgr4Wj8Y",
  "わたしルネサンス": "k9qFnWgtOKw,F4vj6BAyOMI",
  "わんだふる哉、人生！": "VA3LwMd2AUk",
  "わんだー×まーちんぐ！": "KX5XTLdvu78",
  "アイ MUST GO!": "1_6SMZZ67bc,12IuCH05wu4",
  "アイ NEED YOU (FOR WONDERFUL STORY)": "j3SLuqmtr9I,QZpIWB-mOwM",
  "アイシテの呪縛～Je vous aime～": "IJDsXas0azg,iHMWudzYkUk",
  "アイスキャンディ": "",
  "アイドルは、かく語りき": "Iv9a2D9Ssy8,86uCF6NeQIw",
  "アイドルステアウェイ": "bzpsh85asP4,mvtjuhFVdYQ",
  "アイノウ": "Rj62B0Zf_aI,5bayGoEJGGs",
  "アイム・ア・リトル・プリンセス ～お星さまにお願い～": "GMR7RYkyQqo,z8hVH4A06GY",
  "アイル": "J0wuISk6Bxs,rUkfysDKQeI",
  "アイレデッスカ!?": "",
  "アイヴイ": "8MKhf3XngCQ,u-YomJhPSN4",
  "アエイウエオア！": "",
  "アエルシグナル": "q0ECuIJNpZw",
  "アクセルレーション": "bGcU0d66qn4",
  "アスタラブビスタ": "of_J-pt-pgc",
  "アスファルトを鳴らして": "07owxw6zfgc,BvMOtJr56vA",
  "アタシガルール": "EemasV3XQp8,9OzEswEazH0",
  "アタシポンコツアンドロイド": "xVxao8MPfMs",
  "アタシポンコツアンドロイド -北谷光浩 Remix-": "xVxao8MPfMs",
  "アッパレ♪Mahara★Japaaan!": "DwLNgR1_9uI",
  "アップルパイ・プリンセス": "TomMiwhjCE0",
  "アツアツ♪マカロニグラタン": "lPPYYJ5RVNc",
  "アトモスフィア": "lnMhxHAfE9o",
  "アナタのヒトコト": "",
  "アニマル☆ステイション！": "KS_pjTokIgk,WxjbEwVbBgU,aD6IvmFXBDg",
  "アニマル☆ステイション！(YUC'e Remix)": "WxjbEwVbBgU",
  "アフタースクールパーリータイム": "TAT6N1nACZk,ax8ZZXt44kk,3ZFy8eJpHsI,MyZry4TxgqI",
  "アフタースクールパーリータイム (TeddyLoid Remix)": "3ZFy8eJpHsI",
  "アプデ": "MpwHtEwtoFw",
  "アポイント・シグナル": "5ZlVL9HMroc",
  "アマテラス": "mR5jxE1vycE,Qc4zVz44QXg",
  "アムリタ": "",
  "アライアンス・スターダスト": "Kn-srr_Z3J8,G4NN6E-GikM,DaKYdxn_ifI",
  "アライブファクター": "efXIu65q9W0,tyEKWvF7lfI,Ro1E62Quneo",
  "アルカテイル": "og1nyKN5I5Q",
  "アルストロメリア": "9LP-l20jhWI,l6uy19R0K2g,dDIeDi-NlGQ",
  "アルティメットアイズ": "94sdoCCjYY8",
  "アロー彗星": "gidMDQz5lzE,4KBbX6qDGNk",
  "アンデッド・ダンスロック": "rjqlh5kXjP8",
  "アンバランスなKissをして": "",
  "イケナイGO AHEAD": "GgEEHy9FPBo",
  "イジワルしないで 抱きしめてよ": "t2_W_14pAIc",
  "イタズラなKISS": "",
  "イチバンボシ": "",
  "イリュージョニスタ！": "4-mRTig2Ysc,d4rkrNDFYC0,cIbF2jIT6qA,yakdUDvZR5Q",
  "イルミネイトコンサート": "6-OZG6vJj3w",
  "インセインゲーム": "9KnQrZsIs4o",
  "インドア系ならトラックメイカー": "_-9e8orRZ2A",
  "インヴィンシブル・ジャスティス": "J723VG6_lsI",
  "イーリャンサンキュー": "7Yg1Flr1PDQ,nAW43k01ais",
  "ウイスキーが、お好きでしょ": "",
  "ウェイ・ダ・アイドル": "MQmt8mYtkSA,cABx8Wl9YAw",
  "ウルトラ リラックス": "QeIz-YN11QY",
  "エウレカダイアリー": "h5pAoqdvBZk",
  "エキストラレボリューション": "_rQ6yDLakdo",
  "エキセントリック・ラブ": "zBmNvRC6JgY",
  "エスケープ": "nM0abUHU_MI,6EBlEhSMrZU,b9LN6whqhS0",
  "エチュードは1曲だけ": "kNuOBdC7f7M",
  "エピソードラブ": "",
  "エンジェル ドリーム": "",
  "エンダーエンダー": "g8j_o_Uo6AA,VLobhrJimp0",
  "エヴリデイドリーム": "3UPwsxPNn20",
  "エージェント夜を往く": "xlO5s3dOBLs",
  "エール": "",
  "オウムアムアに幸運を": "lUJJJXwfpV8,NulTPXZtR2g,XNEMgCjHO0w",
  "オタク is LOVE!": "igUC0GWLKcM",
  "オトメゴコロ更新中": "UPucP9P6r98",
  "オハヨ○サンシャイン": "",
  "オモイノウタ": "QLLCCH7kDWI",
  "オヤマトペ♪": "oJ_OhrPHOfc,MKhVgLa6K5Q",
  "オリジナル声になって": "o9dL5JojRNE,_QqEOE8GnDs",
  "オリジナル声になって（DÉ DÉ MOUSE Remix）": "oKP2NQ_2owk",
  "オリビアを聴きながら": "",
  "オルゴールの小箱": "uYszZtEqQ1c",
  "オレたちの最強伝説～一世一代、破羅駄威棲！～": "jhhLtuJVSds",
  "オレンジの空の下": "leZqkdYIseU,vxBs56cg4ZY,Ih6Mi3YwBEc",
  "オレンジの空の下（チバニャン Remix）": "vxBs56cg4ZY",
  "オレンジタイム": "JDZ_ESQk1I8",
  "オレンジノキオク": "v5TaSvXAlSA,7zYw68xm7OM",
  "オレンジ・エピソード": "4OiEIHsaYeI,pxNDyVpG7m0",
  "オン・ステージ・プレーヤー！": "QSg9XoKjxIU,KfJ4x-Oruvg",
  "オーディナリィ・クローバー": "4InSPPZSdx0,_kasUXGaa3s,IHcdp3NhD5M",
  "オーバーマスター": "1s991iWsyjE,UqCsxH_CRLE,JdaHa60417Q,ZaKqMQ8h47M,_Ks29K7oOTI",
  "オーロラ・モーメント": "HOd8xsxaF34",
  "カウントダウンラブ": "YTEfWavFIvI,jrM0xASC6os",
  "カクシタワタシ": "m1T7EfqoU3Y,SqTcK3wLRoo",
  "カタマリオンザドゥン": "YBI8JjoWPhI,V0-j7De3-2s",
  "カナリア諸島にて": "",
  "カプチーノ": "",
  "カラフル・シンメトリー": "d4SIAWrqOw4",
  "カレイド TOURHYTHM": "yKUteR04wGI",
  "カワラナイモノ": "dcx5UniwoKA,rSw9ihvCynA,kT1YG0fDg7I",
  "カワラナイモノ (DJ WILDPARTY Remix)": "MPiFpxb4ZFI",
  "カンゲキハッピーエコロジー": "",
  "カンパリーナ♡": "vEIImq85rys,6cFkEZq-PgY",
  "カーテシーフラワー": "gL3SigAToAw,GvI0BkOHHZ8",
  "カーテンコール": "",
  "カーニヴァル・ジャパネスク": "mdKk4Owj9oQ,jazWl_Z8y1U,NamwZszOeAs",
  "カーニヴァル・ジャパネスク (チバニャン Remix)": "jazWl_Z8y1U",
  "ガッツだぜ！！": "prL6woWpfbI",
  "ガラクタロード": "O9oCfxSJXTY,ucVPQ2KiKKw",
  "ガーネット": "",
  "ガールズ・イン・ザ・フロンティア": "MKWHxSzEBTw,kiFcPyfWCCY",
  "キズナシェアリング": "K2jPxwEWhO0",
  "キセキの証": "8GmZVlkGYIk",
  "キセキ的 STARRY-TUNE!!!!!": "qScNkFPig3U",
  "キミがいて夢になる": "5gEBdRAAVzk,ww5WsIZY7lE",
  "キミがいて夢になる（fu_mou Remix)": "NxfkhZLRehs",
  "キミが真ん中にいた": "ePgqf4nHu4w,rXsvVNOu4N4",
  "キミとセミブルー": "Z-LWjF5J6Mw,NSt1MvglTeo",
  "キミとボクのミライ": "LVo4J-9H16o",
  "キミのそばでずっと": "1kyf4qepF6E,qyx9QRuDzhc",
  "キミはメロディ": "oSl2jWt61ZM",
  "キミ＊チャンネル": "",
  "キャットスクワッド": "K7rfVTsLBdw",
  "キューティーハニー": "",
  "キラッ！満開スマイル": "24RXFvhtCGo",
  "キラピコ.exe": "53Gil3ZLJjc,FVFm9vebdSM",
  "キラメキ☆": "",
  "キラメキラリ": "Fpd4anmCDHU,PingiSKVcEY",
  "キラメキ進行形": "RW8N5k0jxWE,UGVnedMArfY,LcT5EGALfvw",
  "キラメキ進行形(Giga Remix)": "UGVnedMArfY",
  "ギフト": "",
  "ギブミーメタファー": "B8aakRi5uVI,w_R87WNNWMc",
  "ギュっとMilky Way": "zWoakLdmrEs",
  "ギョーてん！しーわーるど！": "AQMx6bL8ypU",
  "クライマックスアイランド": "WAqXExh2r3I,3JQjFkwVo9Y",
  "クライヤ": "1Rlvf8hDpiQ",
  "クリスタライン": "HIRn0J0MGLk",
  "クリスマス・イブ": "",
  "クルリウタ": "1xTKpLnY9b0,-2THbTcoX6E,sEkJbekMfI0",
  "クレイジークレイジー": "KFdgUoX8sWo,8UnIo8Fv4M0",
  "クレイジークレイジー -石濱翔 Remix-": "KFdgUoX8sWo",
  "クロス×オーバー！": "",
  "クロスワード": "",
  "クローバー": "SItf7eLKRWo",
  "グッデイ・グッナイ": "aYL2cm2WCes,5lKi5ZW2elE",
  "グッデイ・サンシャイン! (ケンモチヒデフミ Remix)": "09TekYT_Nls",
  "グッデイ・サンシャイン！": "XGCS8UBJe8I,vNUnfhm3Ifc",
  "グッドサイン": "IP03iH13Wk0,rHhI1CBowQg,nHd0vPafYOw",
  "グッナイ☆スターズ": "",
  "グッバイ": "HxI8csmgT6E",
  "グラデーション": "c5hq1Xxe_pY",
  "グローインミュージック！": "g-DM1z9WK_4,lGex7hvK5kM",
  "グースーピー": "HarHa3gfU4A",
  "ゲキテキ！ムテキ！恋したい！": "8mzMggsQoSY,JQCXCRTaM9o,nQLIA9pzzsQ",
  "ゲンキトリッパー": "Iox3M6bDbdg",
  "コイ・ココロ": "kzVK-RGiHkA",
  "ココ☆ナツ": "soIeUbRf3yk",
  "ココカラミライヘ！": "eSRPtkVOyak,SWdCeRHSv90",
  "ココロ☆エクササイズ": "FKQcRjKUTdk,quOVhisZtbQ,2pBBVjataZA",
  "ココロ☆エクササイズ (TORIENA Remix)": "PSbgEbsn4Tk",
  "ココロがかえる場所": "DcsHvTXlQbc,0-ON3SNGdFQ",
  "ココロがかえる場所（ケンモチヒデフミ Remix）": "5ObP1x_gNmo",
  "コンテンポラリのダンス": "Ll2y8jgus_s",
  "コントラスト": "HHsxuzP5IXQ,4a6oeXjh8-E",
  "コーヒー１杯のイマージュ": "",
  "ゴキゲンParty Night": "3395tnmQDn4,-BLh6bDnHQk,QmtMdOCucTM",
  "ゴキゲンParty Night -Dance!!!!!!!!!!!!!!! Remix-": "pGSha5LzA54",
  "サイキック！ぱーりーないと☆": "wgcMiTFSSl4",
  "サイコーCOUNT UP!": "gh1RKrQqJWU",
  "サイレント ナイト": "",
  "サイレント・イヴ": "",
  "サイン・オブ・ホープ": "hrS7uoQSSoY,Zo6cCCyjyCg,z13_4ZvvPEM",
  "サウンド・オブ・ビギニング": "Dx9FOIXrF10,cNqGtiVFkrQ",
  "サニー": "-TaNTNv67X4,rYU1V5fNjKQ",
  "サニードロップ": "4kmmJaEjg3s",
  "サマ☆トリ ～Summer trip～": "aYOk_3fDaD4,hZnIlUtKZfE",
  "サマ☆トリ ～Summer trip～ (チバニャン Remix)": "MTdZgfXTumg",
  "サマカニ！！": "SVWdrDswz5I,KBTnPXMHNPQ",
  "サマーサイダー": "atJPNDR0Zwo,pSP1A9EbSl4",
  "サマーサマーオーシャンパーリィバケーション": "7Y09AHX21ko,4cALKy06X1s",
  "サヨナラバス": "qgFTEkT_xdc",
  "サラバ、愛しき悲しみたちよ": "ELZwfQW8ZJ0",
  "サンタが町にやってくる": "",
  "サンタクロースはどこのひと": "",
  "サンフェーデッド": "XLwmEuM0dIw,kznwaqv80yg,oi0foyZWgUo",
  "サンリズム・オーケストラ♪": "lpsFTah9bVw,YTbwRWjcn8c,XGo-J74Rdk4",
  "サ・ヨ・ナ・ラ Summer Holiday": "iau4X5g7yJg",
  "ザ・ライブ革命でSHOW!": "TmarA-jVo1I,ccaXm8y8PaQ",
  "シャイニーエクササイズ": "",
  "シャイノグラフィ": "Rwyq7IV-lLo,Bsm9rQc7uew",
  "シャクネツのパレード": "MRrKpErksy0,CCLUR0uGL9E",
  "シャララ": "8X0FuRWFbdU",
  "シャル・ウィー・ダンス？": "9SHHAgYhs7I,fZKzQ_LWig4",
  "ショコラブル＊イブ": "jrXRStmE-to,mAT-tx5xWpQ,HxQe5SVHlWQ",
  "ショコラ・ティアラ": "c4cjuPDInlA,ILBWUmDlO28",
  "ショコラ・ティアラ -Before Sunrise Remix-": "",
  "ショコラ・ティアラ ～For Miria rearrange MIX～": "",
  "ショッキングな彼": "12fPhKMMtSk",
  "シルエット": "Ux8buSQF8W4,ugFmYtvrkwg,RGGeF8e3PwQ",
  "シンデレラNo.1": "jRN8wLjkBPY",
  "シークレットジュエル 〜魅惑の金剛石〜": "rE8r5eTCNbw,RucR1wpj99A,Ik7E0h3zfR8,EY_ujI6vBt8",
  "シーズン・イン・ザ・サン": "",
  "ジェミー": "8yJTW9FoGlk",
  "ジャングル☆パーティー": "xwU0GKZ1rkQ,ZWw2ZbQ7rpA,4Gtnv2NRiGk",
  "ジュビリー": "TRS26RbOorQ,oYPsnN_6HVM",
  "ジレるハートに火をつけて": "DE8mRE6alvI,o-Es4M6OgNk",
  "ジレるハートに火をつけて（4sk Remix)": "DE8mRE6alvI",
  "スウィートドーナッツ": "",
  "スカイクラッドの観測者": "SPCw4-meZS4",
  "スカイスケープノート": "K0YN_1gzVcA",
  "スキ": "",
  "ススメ☆オトメ ～jewel parade～": "2pIMGpqBjuk",
  "ススメ☆オトメ ～jewel parade～ - しんげきRemix -": "",
  "ススメ☆オトメ ～jewel parade～ -Blooming Floral Remix-": "",
  "スタ→トスタ→": "Ho996SjRqSI,u9DzjhBRwrQ",
  "スタンドアップ（正式表記不明）": "",
  "スターチスを束にして": "1xUozxqsqwQ",
  "スタートリップ": "RDeldVk0w0IFY,gGkupQg3-Uw,W-HtU9-aFs0",
  "スターライトステージ": "LI7K-KBAxiM,SV9yxb9rEek",
  "スターラブレイション": "Yz2EdMQvrgA",
  "ステキハピネス": "",
  "ステップ！": "rKctwc2In6c",
  "ステップ＆スキップ": "2V7YraAIfl0",
  "ストリート・ランウェイ": "EFzec-BolWs,j8-NxgR24uw",
  "ストレートラブ！": "",
  "ストロベリー・キューピッド": "fqAgsodLfkw,5bgaRTDdK6A,bclEobFcc7A",
  "ストロベリー・キューピッド (TeddyLoid Remix)": "w8viUwp0_j4",
  "スノウレター": "xfaj9Opwv1I,py_tHyAZ0hw,w6qVXhmmhcA",
  "スバル": "6it2HDsSQD4,u5jKiZ-dhOg",
  "スパイスパラダイス": "z8BZp6yoJrQ",
  "スパイスパラダイス～カレーメシver.～": "gGEfrnw4-Rw",
  "スペードのQ": "m3cDRMCGuoM,YZvit788Ds0,43-axjPdNFc",
  "スポットライト・ミラーランド": "mze8bxMlVik,EEj3iUEmt-k",
  "スポーツ！スポーツ！スポーツ！": "_HpZa2mavkU,XExPniomTI0,_44ejm9cfUM",
  "スマイルいちばん": "FteLusW-JhY,ovOvZ6N9KUE,uDVa6jMMaZg",
  "スマイルいちばん (4sk Remix)": "ovOvZ6N9KUE",
  "スマイルシンフォニア": "4yHRdQB30S8,Mz-aNqtPdC8",
  "スマイルファンタジー": "ovu6Al6aWes,SmgNZwVO4YY",
  "スマイル・エンゲージ": "NZvFnOVkSFE",
  "スマイル体操": "",
  "スマイル体操（ピコピコ体操バージョン）": "",
  "スリーブレス": "YpCKjHP1Xfw",
  "スローモーション": "R0o7QrybbCI,nZyNbYoqlxI",
  "スローライフ・ファンタジー": "ooVacNKo51U",
  "セイクリッド・ブーケ": "LhD31Hr1hRw",
  "セクシータイフーン": "M8xqZCpzYCU",
  "セピアカラフル": "4UiX3Oqi97A,CSWbkYEChq8",
  "セブンカウント": "_XKtVD8z5aQ,EhGYp5JLvOk,C38cR8TDRHk",
  "セブンデイズ・アルペジオ": "-4Kjk2iWgNo",
  "セレブレイト・スターレイル": "INt3dl_QNa8,xewRMK00Xm0,N595kPuUGFg",
  "ゼロトゥワン！！": "",
  "ソウソウ": "IQ1yV92mATI,4vQwruUttL0",
  "ソナー": "gyJ2VZpAAqg,DMAXmP-x2ic",
  "ソライロ！": "9clXtITViac",
  "ソワレ": "zVvjwhT-yB0",
  "タイムマシンに飛び乗って！": "HiF8f_egY2A,HsHoI4ou_uM,aSIgYoxvM3Q",
  "タイムマシンに飛び乗って！ (TeddyLoid Remix)": "HsHoI4ou_uM",
  "タソガレドキ、Bluesy": "A0lRPIhs9gg",
  "タッタ": "-1rPN1l_gAk",
  "タッチ": "",
  "ターンオンタイム！": "D7eYTX-nNUQ",
  "ターンオンタイム！ -MR remix-": "8Xhe5rQbDcs",
  "ダイアモンド・アテンション": "6ChpMU-hJwo",
  "ダイヤモンド・クラリティ": "_yw_1d_nGeA,NHUfat2ksgk,kd2yj_W0KCA",
  "ダイヤモンド・メゾフォルテ": "h195qrcoMko",
  "ダブル・イフェクト": "qXMig02NZno",
  "ダンシング・デッド": "mqB1F8QsUUw,qWR58MIJmXI",
  "ダンス・ダンス・ダンス": "hGcJR7Fw764,g032f2lciLo,m5ntKaBEL_M",
  "ダンス・ダンス・ダンス -ミフメイ Remix-": "cPXDMq8i6eo",
  "チアリングレター": "7DzJWQx0urs",
  "チェリー": "jvf5bRPwaUM",
  "チカラ！イズ！ぱわー！！": "pUkghDdu39w,crCA82PmX8Q",
  "チキンライス": "",
  "チクタク": "3iNVoWoh4Vc,f-VWO-ZArpM",
  "チャンピオン": "",
  "チョコデート・サンデー": "qhPQxztoky4,RkIydkM0A1k,JUvpDPykqnw",
  "チョコレート？レモネード？どっち？？": "vctPgHMKQ-o",
  "チョー↑元気Show☆アイドルch@ng! (Giga Remix)": "",
  "チョー↑元気Show☆アイドルch＠ng!": "SDJi-2RfvOA,X4RUKDmB6Gg,KyFc-nqjR_g",
  "ツインテールの風": "oAOpHcdIz8U",
  "ツキノカメ": "E74wm1P6CPI,h0RCuBQRbLo,6TZKFFRzwzs",
  "ツキノカメ (Shinpei Nasuno Remix)": "",
  "ツバサ": "",
  "ツバサグラビティ": "1V0_81XYS8M,nf8UXk8FuJo,Ak8BBUfvpJg",
  "デコレーション・ドリ～ミンッ♪": "zz51dRsOefE,8xFLIZoQEGA,NMrRGNGAmpc",
  "デコレーション・ドリ～ミンッ♪ (TORIENA Remix)": "8xFLIZoQEGA",
  "デビ太郎のうた": "",
  "デレぱにぱにック": "dgslQyX7noc",
  "デレパの神曲": "",
  "デレパノココロ": "t_v_FIf1ci8",
  "デレパノココロ -DJ Remix version-": "t_v_FIf1ci8",
  "デレパノココロ -Radio Remix version-": "t_v_FIf1ci8",
  "トイレの神様": "",
  "トウキョウ・シャンディ・ランデヴ": "EJr1zztHA9E",
  "トキメキの音符になって": "VhXQPwbaiN4,qNh-OXzP3PU,HnxtCPSnRiI",
  "トキメキの音符になって (nyankobrq Remix)": "h9sNdmoBvrU",
  "トキメキは赤くて甘い": "3Fzobwa1nMg,eyH_zO_qgHM",
  "トキメキ・ぷろろーぐ！": "l211XnIs-Ng",
  "トライアングル": "lcwu-Vcw9Js",
  "トリプルAngel": "1tsqhWOksRg",
  "トレジャー・パーティー！": "viYnszW0PU0",
  "トレフル・ド・ノエル": "l4llQN5Zl9A,kM3zNTzkXj8,iBhyy2F-lx8",
  "トロピカルガール": "SCkAIDtC_dY",
  "トロンプルイユ・ダンスホール": "FDVk40FsEAA",
  "トワラー": "gUBiL1oNXKQ,AirmRu1nK-M",
  "ドゥー・ユー・リメンバー・ミー": "",
  "ドキッ♥ラブアトラクション": "",
  "ドリームトラベラー": "6q0ThB6miZ8,Xci96gKNeSk",
  "ドリームトラベラー (picco Remix)": "6q0ThB6miZ8",
  "ドレミファクトリー！": "MrEZ-SydOFk,lX8LhGhIYn4",
  "ナイワ": "XLD6CBji5kY,F-JRSzq4zuo",
  "ナツゾラRecords": "gfYCXiMMWkQ",
  "ナツノハナ": "",
  "ナンダカンダ": "ye4XX0MJfoU",
  "ニッポン笑顔百景": "Mmd95cj6tDc",
  "ニャンと☆スペクタクル": "QL8LmRwR334",
  "ネコドル☆オーバー・ザ・ワールド": "6IpfY1bOL-I",
  "ノーチラスソナー -Nautilus Sonar-": "o483LjpIbe8,8entqzKt0Bo,siO29ZjXxm8",
  "ノートの中のテラリウム": "spPnSbKSndw,PuBNemagm_4",
  "ハイパービリーバー！！": "nuG-_5JYViY",
  "ハイファイ☆デイズ": "kUc_lv35ci8,v9XZdo8Tbvo",
  "ハグしちゃお": "",
  "ハッピー☆マテリアル": "",
  "ハッピー☆ラッキー☆ジェットマシーン": "PoYzP7uR_q8,QKksrhOaBI0,sZ--IpFyYJc",
  "ハッピー☆ラッキー☆ジェットマシーン (KAN TAKAHIKO Remix)": "QKksrhOaBI0",
  "ハッピース": "",
  "ハッピーマイガーデン": "LyvNqx75d2A,I0HiUDoF7x4",
  "ハッピーミルフィーユ": "AON5aAVG3QU,6R_u9s9xvqY,V6EyC7SGoNI,HKtQHUAIWbE",
  "ハッピー・ジャムジャム": "JVOGPBmE7oU",
  "ハッピ～ エフェクト!（チバニャン Remix）": "kiEWgqxNNNs",
  "ハッピ～ エフェクト！": "mmZubakspio,y8yrzbyIE2s,Wpwz0dIsV2E",
  "ハナサカサイサイ": "VmRdanB0i6s",
  "ハナビラメールの空": "Hn80wA4f6vc",
  "ハナマルバッジ": "_LQZ4HUQESU",
  "ハナムケのハナタバ": "HfZSEqxjAhQ,3jOvQgCqj2I",
  "ハニカミ！ファーストバイト": "bbWulQidKY0",
  "ハピガ！": "k0teIiJC83c",
  "ハピリリ": "n_synseUdIg",
  "ハミングがきこえる": "ycp6a4FhKfk",
  "ハミングバード": "4KaX4It9mjw,UzG-ZjDgunM,OAYLyycXqDQ",
  "ハミングロード": "85gHiYvY55A,fy2Gk5fgRlU",
  "ハミングロード（チバニャン Remix）": "85gHiYvY55A",
  "ハリキリ★ラリー": "",
  "ハルカナミライ": "pSWhziFJAAw,khtfRhMDxTI,TtCk0ghvF90",
  "ハルマチ女子": "RYe9pPW-sXc,cRbeNebyR1U,BQDLLTu-dOc",
  "ハレ晴レユカイ": "JUnfAcOR-Ss",
  "ハロー": "6pgyI0315Zs",
  "ハロー*ランチタイム": "",
  "ハローハイドレンジア": "ozGHpUP7pQM",
  "ハンドメイドスマイル": "v6L2bq7HTvI",
  "ハートウォーミング": "IGWVBofQYTA,z9c9RtTLVP8",
  "ハートウォーミング （DÉ DÉ MOUSE Remix）": "z0q3bpr1dpE",
  "ハートフル・パトローラー": "lEQci3hpsxU",
  "ハートボイルドウォーズ": "glJes90Swis",
  "ハーモニクス": "uGNYcvSTHc8,K4UJsSQbaFE,zWiEWaQSB4U,RQ_sxZw1f9A,tVT73cqQ71I",
  "バトンタッチ": "dvWZcS_5Tr8,tY47Dt4n66c",
  "バベル": "X8viYNLC6Ow",
  "バベル -ゆよゆっぺ Remix-": "WHiEwP7kfDE",
  "バベルシティ・グレイス": "ZeHEgsy_eBQ,3c_xE1FR9Lo,EvUEsSzLq1s,xijlX5QvO88,cPh82K-yMl0",
  "バラカストーリア～月と太陽に祝福を～": "rO5P-rtQBM0,haLVft6iYr4",
  "バレンタイン": "1aJDwRXK7H4",
  "バレンタイン・キッス": "",
  "バーニン・クールで輝いて": "GCO6R0rDn-g",
  "パジャマジャマ": "0XSnAacmJ7I,g-BA3EPDfiU",
  "パステルカラー パスカラカラー": "VyzV-6UWq8U",
  "パステルピンクな恋": "lDW-XF6ifxo",
  "パラソルサイダー": "u8ARQGjiwXA",
  "パンとフィルム": "r0nrUmSBDIE,jx5cYVRF__s",
  "パ・リ・ラ": "f_ibcmC3Y6Q",
  "パーティーマジックデザイナー": "i2bLzPugsn4",
  "パーフェクトゲーム": "UBwNuecQZmo,i734-lMvbwA",
  "ヒカリ→シンコキュウ→ミライ": "fzuREykXFFI",
  "ヒカリのdestination": "wjQGpudph_8,SeNiJ-4azcY",
  "ヒカリ待つ明日へ": "hH99B6MTm38",
  "ヒトトキトキメキ": "u0p-CGszIZI",
  "ヒミツの珊瑚礁": "",
  "ヒーロー": "iU9NQ-__oB8",
  "ヒーローヴァーサスレイナンジョー": "lOpGxaFe8d4,1PUGTCXkFK8",
  "ビギナーズ☆ストライク": "G4kY0d4yK7k,Q4OWJQQ90is,xG9WT0z6zec",
  "ビギナーズ☆ストライク（チバニャン Remix）": "PcMQVlW0MNA",
  "ビジョナリー": "eTTNK02EKFU",
  "ビッグバンズバリボー！！！！！": "Xs-mB6nFMV4,ecvzLOosSzg,HQEni1T3t7M",
  "ビーチブレイバー": "H7UnV749yPQ,BXp0D3gdrrY",
  "ピカリピックアップ！": "xFxVKnmlqw0,10Kevs_wDPQ",
  "ピコピコIIKO! インベーダー": "qAV5I5a3vz8,fLaHWY13Blc,jCQLfTDCwSM",
  "ピコピコIIKO! インベーダー (MOTTO! 幼年期-mix)": "5r3JMspSsL8",
  "ピピカ・リリカ": "8uot4h72uso,i9g_PHq2wrU",
  "ピンキージョーンズ": "Yrqz62NkBmk",
  "ピンクローズアプローズ": "UkGjJrRkTb0,d9JE0w5AudU",
  "ファンタジスタ・カーニバル": "vkgH2vsTOi0,i264aqP2P18,h7RJMfR66og",
  "ファンタジスタ・カーニバル (Tsubusare BOZZ Remix)": "i264aqP2P18",
  "フィクション": "_7PGAeZxMPY",
  "フェアリー・ガール": "U9DGtsSZC6c",
  "フェイバリットに踊らせて": "pujWZebTrOU",
  "フェスタ・イルミネーション": "tIWoBraJkus,ELmWTpuqGOw,6awC7_ahQLY",
  "フェスタ・イルミネーション (Getty Remix)": "KNy_cqT3p-Y",
  "フシギトラベラー": "y9_kIGzCOTc,k5-Wuuw5D00",
  "フタリの記憶": "irCfEX1htd4",
  "フラワーガール": "JE6gyD4fLaE,FTBT4U9v_9w",
  "フリースタイル・トップアイドル！": "BDXOLhYAMYo,BZtwa3rHgX0,cMvb40caGao",
  "フレデリカ、猫やめるよ": "m8jYx9WiTDY",
  "フローズン・ワード": "4pyY2AtMghU,SuXoN_7ZjpQ,W0DrfoAu4Ck",
  "フローズン・ワード（y0c1e Remix)": "0m5NyLk16aw",
  "ブルウ・スタア": "LcfNP2jtlwk",
  "ブレイク・アウト・セレンディピティ": "lHAfNSFvYB0",
  "プライスレス ドーナッCyu♡": "WY20UkPCsws,XF5L2csl_4w",
  "プライヴェイト・ロードショウ (playback, Weekday)": "KCSYqpBB48E,lbbtZN2RsxM,voM1UDGbbe0",
  "プライヴェイト・ロードショウ (playback, Weekday) (y0c1e Remix)": "M2RmpzlybNk",
  "プラスチック・アンブレラ": "UqPQbAJUhBM,xkNmOk9yQ8g",
  "プラニスフィア ～planisphere～": "tRbXq3YHuTI",
  "プラリネ": "hjgpHqtHfbw,8q6TvO1ydfE,0Df4P7Gbpow",
  "プラリネ (Dummy Dog Remix)": "Py9AXSN0XWA",
  "プラ・ソニック・ラブ！": "wl9mh0jEwuo",
  "プリコグ": "",
  "プリズムフレア": "RnCJv5ueK3A,JP0F1eCWHmo,-ZBtIIQGXRk,oi8LN7cDF1c,sXTPgytaLuw",
  "プリティ～～～ッ→ニャンニャンッ！": "iAjM5e_8nu8,21LtnbJg-tU",
  "プリティ～～～ッ→ニャンニャンッ！ (BEATNINE Remix)": "",
  "プリムラ": "B2gVFUaLDPY,0A4g2gtRxm8,-4lbOKFRk2k",
  "プリンセス・アラモード": "YyvYMx5G--w,89n2XIdKFSw",
  "プルメリアの花": "Wh2iAlXdci8,6H9HzUqTeck",
  "ペッパー警部": "",
  "ホウキ雲": "",
  "ホップ♪ステップ♪レインボウ♪": "jccOzBNDImc,0wsEN3k0iYs,6KeP8iWBmKQ",
  "ホップ♪ステップ♪レインボウ♪ (4sk Remix)": "vXjISwMZJdA",
  "ホムラインビテーション": "I4rG3Q-OkuE",
  "ホントウノワタシ": "r-XhrkHDb_I",
  "ホントウノワタシ（y0c1e Remix)": "iSlsRhJXDjw",
  "ボーダーレス・ノンストレス": "Oaj6jo_LKLY,_jN1gBX6dLc",
  "ポジティブシンカー！": "Xc_O_TRaRdU",
  "ポジティブ！": "NGK_IfyaOKo",
  "マイドラマティックヒロイン": "okCykUN8mIE",
  "マイペース☆マイウェイ": "vSA5IVXAnqQ,3J-r2HGEIKQ,YBUfZwasnVk",
  "マイペース☆マイウェイ（DÉ DÉ MOUSE Remix）": "3J-r2HGEIKQ",
  "マイペースでいきましょう": "",
  "マイ・スイート・ハネムーン": "TGTSkpdh-eg",
  "マジで…!?": "1VUL4qfRABg",
  "マリオネットの心": "m6zOSzkaXBk,jvRINooXlFo,HNsSnrxIsRw",
  "マル・マル・モリ・モリ": "",
  "ミスティック・セレモニーへの招待状": "wMDFBvBjdtY,WGYtZOyuy8Y",
  "ミステイク・マーダー！": "hartC5AzHWE,gWhoeEfsvVo",
  "ミステリーハート": "5JgCMjEy2-A",
  "ミツボシ☆☆★": "3cWlLgMYZq4",
  "ミツボシ☆☆★ -Happily Ever After Remix-": "",
  "ミツボシ☆☆★ ～For Minami rearrange MIX～": "",
  "ミュージアムジカ": "UMBbzMqM7CA",
  "ミライコンパス": "NF48cFAzCHo,lkHqgdxMGjM",
  "ミラクルテレパシー": "noBqHGiEDDw",
  "ミラクルナナウ(ﾟ∀ﾟ)！": "dp-x87l413o,fD6Ylm3LUAc,ynFvouq-jBk",
  "ミラクルナナウ(ﾟ∀ﾟ)！ (佐藤貴文 Remix)": "",
  "ミラージュ・ミラー": "RUa4k5XjF4U,X70LJ4fg9rY,baO4CubG1zg",
  "ミラーボール・ラブ": "aLwkU-58hUg,ekazeq081bk",
  "ミート・ユメノトピア": "A_Fc_mkI2Cc",
  "ムゲンダイグロウアップ！": "4-dpuorB8b",
  "ムーンゴールド": "JMDNwLvi-28",
  "ムーンライト・プロムナード": "",
  "ムーンライト伝説": "",
  "メクルメ": "DLkNQgh4Ons,vG5_bwL7UkI",
  "メクルメ (PASTASTA Remix)": "",
  "メサイア": "5AopKY7vUZY,mRoP2ewBoOk",
  "メッセージ": "T-gYx2MpQRQ,ZEgKt8NoERA,Q-6p2pkQrqQ",
  "メッセージ - しんげきRemix -": "8K53EWqdZyI",
  "メッセージ -Future PicoPico Remix-": "-Xp_CliwJII",
  "メトロポリタン美術館": "ZGUq6n-JOZ8",
  "メメント？モメント♪ルルルルル☆": "lsrEKhC44cU,D-CIn8cyBBM,-uns7Hxx-Z8",
  "メモリーブロッサム": "VEWUt_IbUKU",
  "メモワール・アンタクト": "M6R4g87-qzc",
  "メランコリニスタ": "146zvNzk3Jc",
  "メリー": "kgiF_-y12xk,WMyYpU7MZEY,7Dynw54ckxg",
  "メルヘン∞メタモルフォーゼ！": "cseoA5osMMk",
  "メルヘンデビュー！": "",
  "モザイクカケラ": "XCpwAyKi5qc",
  "モラトリアム": "wnbihn9sMmI,Na59vHBIcno",
  "モーレツ★世直しギルティ！": "MH7U5qNH8Xw",
  "ユニゾン☆ビート": "HEfidXyPKeA,wvBnc9w7xZk,aNVZC_eumJ0",
  "ユニゾン☆ビート (picco Remix)": "u-4J4MVMakQ",
  "ユニーク・スター・プレイヤー！": "AH-cv_r_7js,bXTRLaDT_Lg",
  "ヨルニテ": "X1xcOhkgc4c,rP-YFrj2PkI",
  "ヨーイドン！！": "",
  "ラ♥ブ♥リ♥": "NJq8UwGDXTA,Q7P1zfvJbLY,n5LezgDLgqI",
  "ライアー・ルージュ": "fwqDRMNHyTk,czuVeXLM51I,VbXmTMPZnew,a3MNRBKTPz4",
  "ライアー・ルージュ (Getty Remix)": "rjLRV236l_Q",
  "ライラックにつつまれて": "gQtzRFDCteU",
  "ラジオ体操第一": "ZMu-VxzyMkE",
  "ラジオ体操第二": "q53PYcuEN3g",
  "ラスト・アクトレス": "xFo1Of_GPAo,bFlVMG8NWQE,o6PjrMZmWcc",
  "ラビットパニック": "",
  "ラビットファー": "QU5wQ-Fqocg,3-KZHARKBKs,YBrpOwQlxB4",
  "ラビューダ♡トライアングル": "DOOGHG3EeZU",
  "ラビリンス・レジスタンス": "FYCvW_4Lqb0",
  "ラブリー": "",
  "ラブレター": "dBbTaM_A0jI,wayBBPAQPaA",
  "ラブ・ボナペティート": "bkbhnhNVRR0",
  "ラムのラブソング": "",
  "ラムネ色 青春": "6cydfPAYEik",
  "ランニング・ハイッ": "6XAbZIyjoFc,0VZzlwxxmOw,iyZD67OXK-s",
  "ラヴィアンローズ": "OMusbxxSd6I,0hOH89YU97U,tTY3lrURnvk",
  "リゾラ": "mH8GIbe7XWY",
  "リトルハピネス": "L0ww4o-rijc",
  "リトルマイシューズ": "ynyVffvZc8U",
  "リトルリドル": "PA4AkZtqWI0",
  "リビングアイズヒーロー": "C0IVZ1IaJiA",
  "リフレインアトリウム": "AUxj0iiJo_c",
  "リフレインキス": "5KUaOtmEMcc,aiW2n48Il2g,0LLssHOMH4E",
  "リフレインブレイン": "wK2Sf0BRpwM",
  "リフレクティア": "",
  "リフレクトサイン": "NP6DbedxYEA",
  "リベレイシング/アロン -LiberaSing Along-": "6yjI0oHA0TE,CDw_a_NLiw8,NydaiqWX2Y4",
  "リルラ リルハ": "",
  "リローディング": "nzkHHR2CUEM",
  "リーチ・アップ・ステップ！": "P8v-X9X5fwc,aXAcapStg_A",
  "ルピラ": "0z5rCRe9Pdk",
  "ルル": "",
  "レイニー ブルー": "wZDTTfGDhjM",
  "レッド・ソール": "gWogCmlAoc4",
  "レッド・ソール -烏屋茶房 Remix-": "3mldNaVfho8",
  "ロイヤルストレートフラッシュ": "",
  "ロケットスター☆": "pz7Gvs9zSBk,k2D3TuakVKs,NG9--qc96Qk",
  "ロックン・オムレツ": "",
  "ロマンティック 浮かれモード": "UK_pmqko490",
  "ローリング△さんかく": "XLa1hhNxSBw,OS_ZP4MtJi0,CrAG42FbE3w",
  "ワタシ御伽ばなシ": "5xzC991Z_KE,Mfl3IJM53ew",
  "ワニとシャンプー": "tB3EH5YT-OQ",
  "ワンダー☆ウィンター☆ヤッター！！": "",
  "ワンホール＝ワンダーランド！": "31WQQXODyoY",
  "ワールド・アスレチック・COOK-KING ～勝者必食！？スポ食の秋～": "66uBeJ7VjzM,NnF2PLRVfxQ,YRQEBBTgdpA",
  "ヴィーナスシンドローム": "iLcGeAPxTjs",
  "ヴィーナスシンドローム ～For Ranko rearranged MIX～": "",
  "ヴヴヴ": "Gk9u5bwp-kY,iNmuKTcSIL8",
  "一体いつから": "PE_iyDsY5xM,XtOneQ4AKAM",
  "一時間遅れの僕の天使": "",
  "一閃は君が導く": "5gC1Acs0sq8",
  "七彩ボタン": "mDn8lKLbjOQ",
  "三分半の創世": "0PWSrVT3wi8",
  "不埒なCANVAS": "Av2mobB7J18",
  "不思議なピーチパイ": "CO-boBKUwzY",
  "不思議発見ラボ！": "na_hb7Ogs-A",
  "世界でいちばん頑張ってる君に": "",
  "世界はそれを愛と呼ぶんだぜ": "OkiDDmixJEg",
  "世界一可愛い私": "cHaEJgn4HYc,WoTY9BO8E5k,xmbEVQnIKjs,6D0n7hzfZiY",
  "世界滅亡 or KISS": "kMUL18NyKlI,um9FN5gn_Ag",
  "久遠の河": "CqdUNF9Fa3U",
  "乙女よ大志を抱け!!": "SwLH2vftBLw",
  "乙女心盗んで！": "",
  "乱舞る": "CHQsfBNN2UU",
  "五ツ座流星群": "zimeUjwomQg,3iISh5nQ9ws",
  "亜熱帯ガール": "",
  "亜麻色の髪の乙女": "",
  "交わる季節": "_aRq0rH_M1E,3Hfh1SFwEdg",
  "人生は夢だらけ": "KzzHZ-PX9V8",
  "今 スタート！": "",
  "今しかない瞬間を": "CC2KWXZtzVc",
  "今宵、笑むように": "_n8L_sBroOw",
  "以心伝心しよう": "",
  "仮装狂騒曲": "8YNzp2vRS9I,4VWNA3ny3T4,DvaxVnHBz0g,ZByf5z5Ecso",
  "仮装狂騒曲 (原口沙輔 Remix)": "",
  "仮面舞踏会": "",
  "仲良しでいようね♡": "",
  "休日の歌 (Viva La Vida)": "",
  "会いたい気持": "",
  "伝えたいのはこんなきもち": "S25k8xA5x6g",
  "似セ者": "zCNzLLWFPjI",
  "何度も言えるよ": "NoeXiU2Y7vo",
  "俠気乱舞": "av1XXFUkYOM,L4wMIoRX5mg,EBJq9789c6k",
  "僕たちのResistance": "4ev1bELS33I",
  "僕はあなたに恋する": "",
  "僕らだけの未来の空": "SkQKSCWmRoM",
  "光": "IQXr22JzbLA",
  "光景": "VJk2etK8I1w,TSuFnypQKKw,8ol7-APhqFY,jYqdVV-uFgg",
  "光跡": "6stRekDKZps",
  "全力★ドリーミングガールズ": "yhhXZzUsX2w,LkdU8cgXgDk,TvN7SULm5zQ",
  "全力☆Summer!": "ZfWrdCklsWo",
  "全力アイドル": "",
  "全力アンサー": "E6lG6sVIyFc",
  "全開！ミラクルアドベンチャー！": "wuyT9y3xJEA,e9qDMZOi-Cg,7auRoEFqjSA",
  "公転周期": "g6yyixyO-rg,s6M84IH4m8k",
  "共鳴世界の存在論": "GQvg3gZ9GNs,dltTZcP0uWI",
  "冒険でしょでしょ？": "ld2TmkUBxq0",
  "冠菊": "E8G7BMd2a7g,AsnMofieWkQ,6Es2sZuWCuo,mK2oLSxaUfA,XqIhCSiRIO4",
  "冬の日のエトランゼ": "2PFvDl91RLw",
  "冬空プレシャス": "SupWNEVklKo",
  "凸凹スピードスター": "EhqZs9H_bWQ",
  "初": "HwZbq2tGguE,w-3PTQLwj4w",
  "初夢をあなたと": "J0OjWxC5Zoo,zCNoFmifE8A",
  "初恋バタフライ": "DWcQYoCCIQc,Bs5xTLeU0Lk,6duRZFWFHYw",
  "初恋バタフライ（NARUMI HELVETICA Remix)": "mWGTiR17o1E",
  "初恋～一章 片想いの桜～": "cvBpbhzeOMA",
  "初恋～三章 幸せの紅葉～": "",
  "初恋～二章 告白の花火～": "",
  "初恋～五章 永遠のクリスマス～": "",
  "初恋～四章 運命のイヴ～": "",
  "初星体操第一": "mhR1G_9cGuA",
  "前向きで行こう♪": "",
  "創造は始まりの風を連れて": "fDkqJ2TP470,YINUSSum3z0,ERbeEEdmzBk",
  "劇星☆戦隊ドラスターズ": "NDljBCrNrEQ",
  "勇敢なるキミへ": "SEcpIbcbHaA",
  "勇気のfragrance": "3al9S4Mnc24,beGZOf1_3hc",
  "千夜アリア": "yK9nNDVpgAg,UDm_PZd3dQk",
  "千夜一夜": "zDtxr7s7mlQ,rpQQbL7ffsg",
  "千夜一夜に瞬く星よ": "AsAYh_dSQks",
  "千客万来ニーハオサァカス！": "CWoYrgCGb-I",
  "千本桜": "62KhA8PjLek",
  "卒業-GRADUATION-": "",
  "卒業写真": "2Bfi2ThXj_w",
  "印象": "KlzjzTUVdIk",
  "友達の唄": "riep6JTOT24",
  "双翼の独奏歌": "F9JtHYbTlVQ",
  "反逆的同一性 -Rebellion Identity-": "8oNzfxDLrQM",
  "古今東西ちょちょいのちょい": "ggdKDQXRV40,nnXCbfmI7zQ,m5TtuoCpHFk,49we3zUjShQ",
  "可愛くてごめん": "JpetpYXF7qg",
  "可能性ガール": "",
  "叶えたい、ことばかり": "rIp3rYd4BzE,WTrdlgJqqAw",
  "合言葉はスタートアップ！": "icCcvbUT_hM,WOBTJX8jess",
  "合言葉はスタートアップ！ (TeddyLoid Remix)": "icCcvbUT_hM",
  "君が選ぶ道": "",
  "君だけの欠片": "0VgwJbkGhOM,yPliJfUhQQc,5d_ZKnOgLoI",
  "君だけの欠片 (Dummy Dog Remix)": "",
  "君との明日を願うから": "HH9-DriaevM",
  "君と同じ物語": "4XzfNJI6JKg",
  "君と咲いた未来へ": "1hXaF6Lq2BI",
  "君に映るポートレイト": "ZA9GjPh01FE,Gn3b4u-SqgA",
  "君のままで": "",
  "君のステージ衣装、本当は…": "AiwUccR6Bog",
  "君の知らない物語": "fkABtaLyBJA",
  "君の青春は輝いているか": "kCF9hh1Iq4U",
  "君への詩": "JmXKozUS1wk",
  "君想いBirthday": "J9xdEXT5V-A,jqUIVgJ_KV8,K4l3klGc9xY",
  "君想いBirthday（チバニャン Remix）": "Qon2J5LeoHc",
  "吼えろ": "oFJmVdi2UDw",
  "命燃やして恋せよ乙女": "uEeNLRYe9iE,BKR1d5fIbYA",
  "和風堂々！～WAnderful NIPPON!～": "OXTH7e6S3Hs",
  "咲いてJewel": "Q0hHBlkHlUY",
  "咲きませ！！乙女塾": "FS5UTC-n4r0",
  "咲くは浮世の君花火": "YaBKNXLOVOg,MesILIppcSw,2mxd07nr4TE",
  "唸れ！ミリオンアーマー！": "nDbuRWZkVOI,D4jnzdP8kB0",
  "喜怒哀楽万国共通―Burn it up!―": "ujAFhvdLYfk",
  "喝彩！～花鳥風月～": "Jy7a7Rfp4AA",
  "嗚呼、情熱に星は輝く～315プロダクション社歌～": "8a2JPD_8iOY",
  "嘆きのFRACTION": "NieE1SfHStg,SsVc5ToK46w,HuO89I7P4ps,RGnkbYOySZM",
  "嘆きのFRACTION (Nor Remix)": "RxLAH8lOVa4",
  "囚われのTea Time": "tcKm3L-U7_I,PTK_6H7ECg4",
  "四心争乱―天地一指―": "aFrmKwSAmYU",
  "団結": "",
  "団結2010": "HmGV5BXETW4",
  "地球ミラーボウル": "lbPdAcD48rA,bBCRrzeCbk8",
  "地球ミラーボウル (TeddyLoid Remix)": "lbPdAcD48rA",
  "地球儀にない国": "bSdj0YkXeVI,iH4FWE-et-Y",
  "堕ちる果実": "bNT-3Z1rlm8,JNSC9uicCxY",
  "声が聴こえる": "",
  "変わらないもの": "",
  "夏のBang!!": "iNXYVVdAAfc,Ng3qGT6eEec",
  "夏影": "",
  "夏恋 -NATSU KOI-": "dA1zUuIO4Vo",
  "夏時間グラフィティ": "D4oLZ6RAJVs",
  "夏祭り": "",
  "夏空グラフィティ": "",
  "夏色": "zPa-Oh5EdQ8",
  "夕映えプレゼント": "ni6ul9_4wIE,RDXt4f9zJYw,_dhWs2--3e0,boM8orI7LUo,dMoxu5e8X54,n2DY5emLXIY,8F-LLzhEiy0",
  "夕風のメロディー": "dsrkzC-_808,_rtOE2bLqqU",
  "夕風のメロディー (KOTONOHOUSE Remix)": "dsrkzC-_808",
  "夜と、明かりと。": "DY8IkWPr8q4,5RJQMBozp08",
  "夜に輝く星座のように": "U0Qiu-YPiu0,Sfo7UwWIleg",
  "夜桜お七": "YX4h4Gfbbs8",
  "夜空を煌めく星のように": "7Y5kA36p1t4",
  "夢が夢じゃなくなるその日まで": "qQBAgzEDYQ0",
  "夢で逢えたら": "",
  "夢にかけるRainbow": "puixYGpcju8,4YvTE_WTgek,bZasJEwFbN4,a5X62ZQiaLg",
  "夢の不思議なラビリンス": "-oXz200GhxU",
  "夢の中へ": "",
  "夢みがちBride": "JCO7mGN0gEA,EZWFjeIwx1A",
  "夢をのぞいたら": "R76roNhqBQA",
  "夢咲きAfter School": "VDPnCL87P1k,lw5WSonuhHw,LxcsFNwQ8qE,0ky-ClgtLrM",
  "夢幻ノ救憐唱 ～堕チル星ノ調ベ～": "gNqferhNfI0",
  "夢模様キャンバス": "lQoDmoMrifo",
  "夢色VOYAGER": "crenZiU_L30",
  "夢色トレイン": "XtSDvkKlv2Y,pBxjzK-DkWs,mS1Gttap71A",
  "夢色トレイン (チバニャン Remix)": "",
  "夢色ハーモニー": "oQid0SoZwxo",
  "夢見る頃": "",
  "夢見鳥": "EweaOmMhwzE,2hQEVSFaQV4",
  "大きな古時計": "4eaVnkXQWU4",
  "大スキ！": "",
  "大河よ共に泣いてくれ": "sGgWLVnA9ic",
  "大都会交響楽": "ermH3UZRAj0",
  "大阪タコちゃんラブちゃん": "y79pTpUBxj0,QD9vOExXupA,D4Be-fFR7vw",
  "天と海の島": "",
  "天使のゆびきり": "",
  "天使の絵の具": "",
  "天城越え": "",
  "太陽と月": "",
  "太陽のジェラシー": "ogStRNLpPSk",
  "太陽の絵の具箱": "d7hQGNQS8n8,tbkD0Tk771o",
  "太陽キッス": "OvILCy8744o,TlMKbphvPkE",
  "奏": "lCF5AfLUvno",
  "女々しくて": "RqCwJHBgZXs",
  "女の子は誰でも": "QMtlK6yj5f8",
  "好きになって、よかった": "",
  "始めのDon't worry": "G-J9WgtcDvg",
  "威風堂々と": "YqbvRrvBmq8",
  "学園天国": "",
  "学祭革命夜明け前": "PyOi2nrevko,KKyeKHDA_Rg",
  "守ってあげたい": "jE60uclc9KA",
  "安寧のDystopia": "QIUNw7bYdzs",
  "実用音楽その1 閉店の音楽 別れのワルツ（蛍の光）": "a51-WCFEECg",
  "実用音楽その2　安眠とやすらぎの音楽 シューベルトの子守歌": "9qx9JKDPpGs",
  "実用音楽その3 祝賀の日本伝統音楽 高砂": "NLoutBoshVA",
  "宵闇のイリュージョン": "BX7xyyD3x7M",
  "小さきもの": "",
  "小さな恋の密室事件": "CYaEg1KkPZQ",
  "小さな野望": "UwA_4TafA_g,P0kX9tBt_dM",
  "少年時代": "",
  "帰り道": "",
  "常咲の庭": "oUNvOafaNIk",
  "平行線の美学": "oqOow1XY9Dc",
  "幸": "KWDlhrB2GEg",
  "幸せの法則 ～ルール～": "",
  "幸燦燦と！": "PMQH-Hkod4Y",
  "幻惑SILHOUETTE": "LI7d7cHjD6I,4LznTKY7XdA",
  "幻想のUtopia": "PG9Mm-EKAII",
  "廻談詣り": "ZXgKRT47zrk",
  "強い女": "",
  "強く尊き獣たち": "fWbXX1WAdU0",
  "強風オールバック": "Y0Zp-Z5EUHc",
  "弾丸サバイバー": "dt9PyDesVks,Kq-6MvHaIAg",
  "彩リノ歌": "yPDIUzQj7yA",
  "彼氏になってよ。": "aXVXlZOjxw8,9BM_MY8oI6s",
  "待ちぼうけのLacrima": "CFI_S_rIJAs,jJ0fNeVdffs,wHZxg-Km69E",
  "待ち受けプリンス": "l88g0SOULkg",
  "徒然モノクローム": "AVnmhhDA_4c",
  "徒花ネクロマンシー": "L3-WSY5UImk,rMFoy17JeE4",
  "微笑み日和": "QEaBBo60Hac,3iuQ8oCHzQA",
  "微笑み日和（チバニャン Remix）": "QEaBBo60Hac",
  "微笑んだから、気づいたんだ。": "wJwh1NUN3Cw,ksbJZF4v4RY,WuLvsvNeifI",
  "微笑んだから、気づいたんだ。 (KAN TAKAHIKO Remix)": "6bJhJ_dVpSE",
  "心もよう": "KHqbGP7NGkM",
  "快盗Vを見逃すな": "5jnVYppFt48,79UOSyf93G8",
  "思い出じゃない今日を": "cKqqYbsGIE0,4T4FeqTcAbs",
  "思い出の花束、二度目の恋。": "ESsTGu6IQ-A",
  "思い出をありがとう": "P-F5rOv9bf8",
  "怪物": "aVMjVDRnfdE",
  "恋": "fmmVqPyDUaI",
  "恋が咲く季節": "v5q6oD6Lv4s",
  "恋するTwist & Shout": "HcV43j22Jts",
  "恋するミカタ": "",
  "恋とマシンガン": "",
  "恋のHamburg♪": "LptLnqffb0U,actLgAFNZJo",
  "恋のLesson初級編": "-GyzLNhO7NQ,36F4fmjFu_I,GESt88EbOxc,yhxuQGGWHTM,_lhVm9XVlD0",
  "恋のLesson初級編（チバニャン Remix）": "yhxuQGGWHTM",
  "恋のWa・Wo・N": "bDKDUCy8dJQ,HRhrDwYUs2E",
  "恋の音色ライン": "aS27KFXLghw,JiUAcCtBw1w,KHO-GguO0RQ",
  "恋の音色ライン (KOUKIISH Remix)": "4EnYsFrRJ20",
  "恋をはじめよう": "",
  "恋人がサンタクロース": "",
  "恋心マスカレード": "3P5nYx3xwew,atHlVO_yg6s,tRcRXrdwdHI",
  "恋心マスカレード (TORIENA Remix)": "atHlVO_yg6s",
  "恋愛サーキュレーション": "SJ1yWJLeJuo",
  "恋愛ロードランナー": "6XsfV2JHp2w,4oA71-PMVDk",
  "恋愛ロードランナー（yuzen Remix)": "iAHnuD1LYj4",
  "恋色エナジー": "-YCnWrRKE8s",
  "恋花": "WKKQrnbix4o,Eit5FWUzaAI,noIbzd8k_QM",
  "恋花 (Snail's House Remix)": "Eit5FWUzaAI",
  "恒久のユニバース": "U1wWuvdeI_g",
  "悠久星涼": "0xSoA53c32c,Ro8bAJ7e298",
  "悲しみよこんにちは": "",
  "悲しみをやさしさに": "",
  "情熱…FIGHTER": "SESzOozkiig",
  "情熱ファンファンファーレ": "L8e84KWB5ao,K2oa-prER5I",
  "惑星が瞬いた夜に": "-NP3vvMwGOA",
  "想いはCarnaval": "Xxs6laAy_fg,JVqYHwGK8BU,0dCwCq7Yjfo",
  "想いはCarnaval（チバニャン Remix）": "JVqYHwGK8BU",
  "想いはETERNITY": "gtGB6y0pH2s",
  "想い出がいっぱい": "",
  "想い出はクリアスカイ": "sPNwrOa4tZA,tOG3i6AT1sY,oWu0LFhYoCQ",
  "想い出は永遠に": "EpmZZIt9xGo",
  "想像のつばさ": "9bLZsXpHsgw",
  "愚者の独白": "31tL35yYFrY",
  "愛 LIKE ハンバーガー": "4xzu8x_SOoM",
  "愛しき日々": "CbE9jUKM-PY,NLfh6MhuM9M,gq1eN8d3778",
  "愛なView": "klcdWCO-GGc,n4dlNkvwLyI",
  "愛について": "",
  "愛のMagic! Once Again!": "KUDszoGpDvE,h4qlMhn96zk",
  "愛のうた": "IIvXpPoyHuo",
  "愛の旋律": "",
  "愛の讃歌": "rjKCYkuZTYI,RnhktxB2srY",
  "愛は元気です。": "ovL1RYkQNuQ",
  "愛より青い海": "",
  "愛笑華！": "HZmqQ-3UOJY",
  "感謝のコントレイル": "_EICx99rxvs",
  "憧れをいっぱい": "y4fR_UBbZVw,XhY07-_kDPM",
  "憧れをいっぱい (Tomggg Remix)": "",
  "成長Chu→LOVER!!": "KFMW3VdhgB4,vp4IlJ1WeF0,JukVboD4a1E",
  "我が混沌のサバト・マリアージュ": "lNM9jNyue5c",
  "手紙 ～愛するあなたへ～": "X3B-WTLp8yM",
  "手紙 ～拝啓、15の君へ～": "",
  "折紙物語": "QDOZI9soVIk,O4CGWp5ZUCg",
  "拝啓タイムカプセル": "aD_jSRh2zHk",
  "推しってほんと": "3LJYBCFrUJE",
  "放っておかないファイヴァーズ": "Z_BpyttvaKI,oLljGG7v1nU,CzBk1WosmRQ",
  "放課後ジャンプ": "",
  "放課後マギア": "hPWqVsQTIf4",
  "教えてlast note…": "DPV8Ofwchh0,dZ-Eu_L6lM4,zqcrKQQ7NR0",
  "散花-sanka-": "3GIhdqrsIMo",
  "数え歌": "",
  "文明開花輪舞 -シティ・ハレルヤ-": "MdHyGhj6MYI",
  "新世代ワールド・ビッグスター！": "la6qJNQmPTg",
  "新宝島": "07tbmkY45sA",
  "旅の途中で": "",
  "旅立ちのコンパス": "PEINhVwvXbI",
  "旅立ちの日に…": "",
  "日々、発見的ステップ！": "scgbx2NKyjY",
  "日々あどべんちゃーなのでしてー": "iHvY8m322yg",
  "日曜日はダメダメよ": "",
  "明日、春が来たら": "",
  "明日があるさ(ジョージアで行きましょう編)": "",
  "明日はきっといい日になる": "98bfayAz_fk",
  "明日への手紙": "m1YfFN3OlRA",
  "明日また会えるよね": "5yJXr4YvZis",
  "明日もBeautiful Day": "qR3yRbrlaCk,XyLA1v_f8Bc",
  "昏き星、遠い月": "idvKPHzCs5Y,Hu5ZRH0biR8,WKnq8DCdD4k",
  "星が流れて": "BbnnR2gIDAY",
  "星のかけらを探しに行こうagain": "",
  "星の声": "OfTLQ5hPc-M,CverFJ90bY0,XV6fnEG2gt4",
  "星の数だけ": "mXiNijnEnjo",
  "星の降る街": "",
  "星をめざして": "RK_5BSEQk5Q,4dP9iLn7Mcs",
  "星宙のVoyage": "SbDazb8934I,YZRodz2CCnc",
  "星屑のシンフォニア": "ZHNJ_zC13XY,R7nLYrMcKDQ",
  "星屑のシンフォニア (5u5h1 Remix)": "",
  "星彩ステッパー": "ymAyXC2guIM",
  "星環世界": "2uz-S2xBOoQ,X5vHJkIT6EU,sF2-s658jik",
  "星間飛行": "",
  "春": "",
  "春の日差し": "",
  "春よ、来い": "",
  "春恋フレーム": "wDNDX2NDxLs,8zTpJPEGQ60",
  "春風満帆スターティング": "R0MgMtPK3h4,lrOtFCSp1PY",
  "時を刻む唄": "o8pv_Rdzli0",
  "時限式狂騒ワンダーランド": "LXyTrPuio-E",
  "晴れのちバルーン": "PiW46jydnkI",
  "晴れ色": "",
  "暗黒への前奏曲": "ZvyeZxpP_Aw",
  "書きかけのラブレター": "RwvFCB5Ll8c",
  "月のしずく": "",
  "月のほとりで": "DeoOeM_A6I4,qYbppL03gdE",
  "月のほとりで (COR!S Remix)": "DeoOeM_A6I4",
  "月のワルツ": "",
  "月ノ桜": "",
  "月下祭～la festa sotto la luna～": "",
  "月影のアンシェネ": "EkmwRqIQcqk",
  "月曜日のクリームソーダ": "XdNJZ_fCX60,8J0pUT5_Uyk,e6xNAh7Wb6A",
  "有彩色ユリイカ": "K6HNtH0wDao",
  "朝焼けのクレッシェンド": "wXzFKYsbgs4,nsYwXATreCA,Iuete84dXwE",
  "朝焼けのクレッシェンド (KAN TAKAHIKO Remix)": "Uu25Hpa5Kmo",
  "未完成のポラリス": "dpji5V-9Xuo",
  "未完成の歴史": "ME_OWi3PjLY",
  "未来の地図": "",
  "未来へのSign": "_tHKr5fdK4A",
  "未来予想図II": "",
  "未来系ドリーマー": "QOXFE2YFdKc,caiYKVL_uTA",
  "未来飛行": "Ikrtt28VhD8,k_-cxBHMIFo,wpCr1PGPaKE",
  "未来飛行 (TeddyLoid Remix)": "k_-cxBHMIFo",
  "来来美食": "EyAcLAxh7Ow",
  "東京は夜の七時 ～the night is still young～": "",
  "枕木の歌": "mG9CMnEswtQ,RMG1LKVzdZU",
  "栄冠は君に輝く": "",
  "桜の頃": "lohJWRrtmaY",
  "桜の風": "pa1u5XwFP_s",
  "桜フォトグラフ": "CcA49B2t7j4,4eVlF7mlj3w,Mt5wOX2MwJw",
  "桜彩": "fbtV79aDNSU",
  "桜色舞うころ": "r5iWnMhKvOw",
  "桜見丘": "cVMjS8euc_8",
  "極光": "hgx-JSSldE4,7ANTx8MZp68",
  "楽園": "ycK-IyZ54Qo,j_5lfToQxJ4",
  "標": "TZ7LwdN--FI",
  "橙より未来": "-qGFQYouceo",
  "歌う人": "Kod1B3BqD7s",
  "歌声は君いろ": "tt0yqJbW2Gc",
  "歩いて帰ろう": "",
  "毒茸伝説": "",
  "気まぐれロマンティック": "",
  "気分爽快": "P0aYFtS31yA",
  "気持ちいいよね 一等賞！": "CTl1BDngldc,0nNiFnc7opM",
  "水中キャンディ": "OJBHG5dB7G0,TfMfICrYtig,kc5lYw7dPTw",
  "水中キャンディ (picco Remix)": "TfMfICrYtig",
  "永遠なる四銃士": "Xp3YhU4VWw8",
  "永遠の花": "-qqGr9LP7RY,mB_j8wOpAHI,4PXouVhBWW4",
  "永遠色アーチ": "jvYfhJ8IEvY",
  "求ム VS マイ・フューチャー": "Cf_06f1GvTw,gBaDlfu5s8I",
  "求ムVSマイ・フューチャー（DJ Genki Remix)": "unxlBxZk4iY",
  "泡沫のアイオーン": "BMx3Qj1tqr4,uGA8DVQwwhA",
  "泣き空、のち": "lT1Vmy7J4aA,MC3QmTFwjWI",
  "泥濘鳴鳴": "LkbTHyLUO4k,CuRIuFRD1zI",
  "津軽海峡・冬景色": "",
  "流るゝ風の如く～和敬清寂～": "A2cXuWB2Xnc",
  "流れ星キセキ": "Ys0JkYhGCoA",
  "流星PARADE": "4P9kgD-pc_Y",
  "流星浪漫": "dDOO-ihax_Y,drLA28AxYbY",
  "流星群": "K0fYPaaGbQM,WnGQqVDFenU,FkbhA3A2ARk",
  "流星群 (TeddyLoid Remix)": "WnGQqVDFenU",
  "浮動性イノセンス": "288td1ES8So",
  "海の声": "mY3HC2CGG_c",
  "海風とカスタネット": "gjisNHmMsZo,_U5IZWpLqNo",
  "涙そうそう": "",
  "涙のハリケーン": "",
  "涙を知ること": "tQwkRBmlcNw",
  "深層マーメイド": "fLhC6EPYbxo,6MvExlWuHH8,uxbm4bA8ew0",
  "深紅": "",
  "深紅のパシオン": "4ht04fYW7Yo,mMqECRRGUB4,JxII3iHsijU",
  "満腹至極フルコォス": "bOIXrwEB_Gc,hIRLBhiJ2Bs",
  "満願成就♪巫女の神頼み！": "Nww-e17Qu_g,1nfk-orgfzY",
  "漢一貫ロックン・ロール": "DY8YjtHIAxM",
  "灯": "JROMJARRPLY",
  "灼熱にて純情(wii-wii-woo)": "sYTkUgXm_8c",
  "炎の華": "nwdaxlsUPds,1jAziZW8Wmk",
  "炎ノ鳥": "SJMr66bMuDU",
  "無垢": "MPSn-S2X6_s,DfiUOdO8otA",
  "無自覚アプリオリ": "Opht82H6qgw,_sZxRSWj9A0,935QayM84sY",
  "無重力シャトル": "TI48rYJ4AD4,k_PYb15kiYs",
  "無限L∞PだLOVE♡": "RcBi6U367tY,xAXHDWSDnDo,lX0hhif0xzw",
  "焼け野が原": "Jw_00DNX31w",
  "熱情エナモラル": "rP7Sego80QY,0upmYzs5J08",
  "熱情！Burning Voltage": "qwt_IwQoLu0",
  "熱血乙女A": "",
  "狙いうち": "",
  "猛烈宇宙交響曲・第七楽章「無限の愛」": "Pi6g0vd51Is",
  "理論武装して": "0ZWUdwVQOJA,EVyc3BnLBWE,lBa3J9E-3_s",
  "瑠璃色金魚と花菖蒲": "YZ_A99vSmPw,RKqrA_dZO4c,8ITEF26Udzo",
  "生存本能ヴァルキュリア": "CgSh5cG-6PM,ZgjH9xoj_ic",
  "産声とクラブ": "EBj1KqX8XZc,wX-sPPF4bc0,s6Q_B_UTDKI",
  "異次元★♥BIGBANG": "3p7__uAHhdQ",
  "疾風ザブングル": "vScTJ37rlso",
  "白い犬": "",
  "白線": "m4VahiqP9vA,pnA9dicgB0I,B48Uw59-2ZQ,9qCDnZY3_G0",
  "白線 (やしきん Remix)": "",
  "百花は月下に散りぬるを": "Z6GJmyL1zSw,59Wngayf-Xg,g15aVRU53rs,Fsic4l8dyh4",
  "目が逢う瞬間": "t458iSCk3Go",
  "相合学舎": "-0kNVfFHvyk",
  "真っ白いページと水彩の主人公": "zpDB6GzOXq0",
  "真夏のダイヤ☆": "4_1bTJQ0PWQ,-Xna92V5S-I,ZWAdDC5Fc60",
  "眠らぬ夜にスパシーバ！": "SueN9velTkA",
  "眠り姫": "YqsM8jMZqlM",
  "瞳の中のシリウス": "m8SHChxIahk,gYqafFcSHkU,HXyVCEMlq20",
  "瞳の中のシリウス (TeddyLoid Remix)": "yAA1y3jwtO8",
  "矛盾の月": "umDMFmRIaoU,bp_Uo5DwIPY",
  "碧いうさぎ": "",
  "碧空ノ一路": "VntCDEB5wSg,bIvjXj1faYk,t-ke4NTXTm8",
  "祈りの羽根": "pewNsrhQT6A,pCug6GmhNy8",
  "祈りの花": "KHOnP8fbrwo,X1k7VifYwQs",
  "祝彩！": "ur7f8AskvyM",
  "神SUMMER!!": "",
  "神さまのBirthday": "RbyY1fQiBCQ",
  "神様は死んだ、って": "4ftrmgThjcY",
  "神様！絶対だよ": "CmPG1LirKVk",
  "禁恋歌": "",
  "禍魂朧夜": "gwaLgn9G0GU,JfyPbFJRNek",
  "私たちはずっと…でしょう？": "JESAEz93wPs",
  "私だって女の子": "wvSMvVZt-eo",
  "私はアイドル♡": "TXrI6iDHBk4",
  "私色のプレリュード": "-ArTPWWrEvo,94slolCcJJI",
  "私色ギフト": "cJbHXQwYWfc",
  "秋の終わり、僕の記憶": "uKWT5M74fyw",
  "秋めいて Ding Dong Dang!": "GPK0-KHz3lk",
  "秋風に手を振って": "kCDYG4cA7gw",
  "秘密のトワレ": "wD3olymAvN0,CDxU-1J2US8",
  "秘密のトワレ -Midnight Lab Remix-": "DlRCFXhbSBw",
  "秘密のメモリーズ": "5CUfTNVBUcY,bSwnKYYQHi4",
  "稲妻スピリット": "YqJKOLeaDc4,2iKBXW1WYZk",
  "究極…FIGHTING": "gWzYU3QFCnw",
  "空": "HNCdUstR9Fg",
  "空と約束": "WxFmsuy4nrM,G8vzMH9c5Xs",
  "空と風と恋のワルツ": "8B7kiEzSSAA",
  "空に手が触れる場所": "HRiPHaNpqs8,BtrxImR005M,_eFnxW1c6cQ,fHYDwlYo7bg",
  "空へ…": "",
  "空想フォレスト": "CzZ0hmgyr5I",
  "空想探査計画": "gmDY836CxwU",
  "空想文学少女": "FWIcPofXa4E,51Uf08SeqHo,hP6WsUrJb3A",
  "空想文学少女 (TeddyLoid Remix)": "51Uf08SeqHo",
  "空色♡ Birthday Card": "z1mA80LsGXs,kKchFxhtSJY,oLIPSy5XvJQ",
  "空色デイズ": "",
  "竜宮逢幻記": "7oan-Y2FZa4",
  "笑って！": "26daXv3i3L8",
  "笑顔のゲンキ": "",
  "笑顔の祭りにゃ、福来る": "BMPonNLwnj8",
  "第六感": "plA4vaOADQ8",
  "筆跡の彼方": "v_gOCSfrxZU",
  "糸": "3zQwUP9mgv0",
  "約束": "QKuQ69jIpvs",
  "約束はドリーミングフライト": "a7lPQlNBxrw",
  "紅": "H7RfHlQE4Ko",
  "紅白応援V": "CHc5S-TIfX8,iQvzj2MnAH4,s6KniJ9qyXo",
  "純♥愛・ジェネレーション": "",
  "純情Midnight伝説": "aktCndP-C2A,KcV68xo-WEU",
  "純情接近STORY": "JWqCp0ektOI",
  "純白トロイメライ": "4h_u95F3ucI,nGIe0kr1r5Y",
  "紙・心・ペン・心 - SHISHINPENSHIN -": "PHLQU0FlVqI,6xEgj2Qidmw",
  "素敵なキセキ": "bJ4C5IS3z9w,viWBiTTXCR0,QNqNXKXir9E,iqKas5YMRPk",
  "素敵なキセキ (KAN TAKAHIKO Remix)": "QNqNXKXir9E",
  "素敵にCon grazia!": "BRWhNex-ibY",
  "細氷": "",
  "組曲―to All Ages Concerto―": "2nHiIataM10",
  "結晶～Crystal Dust～": "",
  "絵本": "6VQO_MgI4UA,fM5fZhd1VC8,qWTLVAmpv3M",
  "絵本 (BEATNINE Remix)": "fM5fZhd1VC8",
  "絵羽模様": "tOoSj9NGkes,JpZ5iLD4S50",
  "絶対正義 EVERY DAY": "",
  "絶対特権主張しますっ！": "ZXM9N84Vq9Q",
  "絶対的Performer": "Kk9nfPmrHd4,onbb-M7R2sY,g0DNTlCam0g",
  "絶険、あるいは逃げられぬ恋": "",
  "縁会！～ENTERTAINMENTS!～": "G4QRC0YvqkQ",
  "美に入り彩を穿つ": "TbE7J-th5ps",
  "美！美！美！ビルドUP!!": "JRBwt6sF3zM,v-8CsWJXrLI",
  "群青イニシエーション": "AeDOs10kBzQ,acjR8k46mKg",
  "義勇忍侠花吹雪": "2_s0ODtTS7s",
  "羽ばたきのMy Soul": "aE-LZeXfSSg",
  "翼": "RTgOCVRNI0o",
  "聖なる夜に": "",
  "聖ミリオン女学園校歌": "s8_pm4Q23RY,lLt3wfTAPM0",
  "聖炎の女神": "Bwk0Pq74ncY,uTqkUMfa1to",
  "自分REST@RT": "wHWGowfW7A4",
  "自己肯定感爆上げ↑↑しゅきしゅきソング": "WCDLyXJgbIo,e2-yH2BTCkM,Fhwbl82WdcA",
  "自転車": "BBIo9kFBJUw,6S2HODPgjak",
  "色・ホワイトブレンド": "",
  "花": "zJpXGz06nsg,Lh-4UeKsM4Y",
  "花ざかりWeekend✿": "QhPBcTdcih0,mkL0Q9aCZhw,PUkiQRzXvCw",
  "花のことば": "pU8Juw4HLBQ",
  "花びらメモリーズ": "IVPd49qiZOE,fN9JRjms8yI,o90keHLiA_w",
  "花簪 HANAKANZASHI": "EdpZSVxXvyo",
  "芽吹の季": "PiUrIXhRWuc",
  "若鯱家CMソングちゅるちゅるうまうま": "kji4BdvGgN8",
  "華蕾夢ミル狂詩曲〜魂ノ導〜": "jWHqOPNrZkg",
  "華蕾夢ミル狂詩曲～魂ノ導～ ～For Anzu rearrange MIX～": "",
  "蒼い鳥": "KXbbZ7T7034,3g2OqaO4Ajs,BLMKfDj4lUk",
  "蒼穹": "",
  "薄紅": "wIJeZg2bqSo",
  "薄荷 -ハッカ-": "eAyeEl05SN0",
  "虹": "",
  "虹になれ": "tOVnK7fnKek",
  "虹のデスティネーション": "LemwARrcMfg",
  "虹の王国の物語〜エトワールを目指して〜": "aQllpVmIgJA",
  "虹の行方": "WGrgo8-8XwY,dc8ng6EB32U,04Ru2pBp2eg",
  "虹色letters": "HHQfc80pzfw,6aB1Tvr8Uo0,Wb9BBYgGE0U",
  "虹色ミラクル": "",
  "蛍火": "7p8wEOHwVow",
  "蝶々むすび": "qMdZaBb7JKo,Ji3NL_HusbY,FGX-Nd942Lg,dIHKDnoMAKs",
  "行くぜっ！怪盗少女": "c0mVbaso3Ig",
  "街角メランコリー": "dyquifCyBzI",
  "装―So Beautiful―": "sQbXgBhyrmE",
  "裏表深層心理": "YqM99bzVha8,PuNY8T0Vx5I",
  "裸足じゃイラレナイ": "qCJaj1apfTM,vI6ofjkxpsE",
  "見つめて": "kXRioFeFhN8",
  "見て": "nKO8cTM9jrI,Am_9JzDesKI",
  "見上げてごらん夜の星を": "6XGDidV_FGg",
  "解夏傀儡": "lKjCC6V3aso,64oWozqhBbo",
  "認めてくれなくたっていいよ": "rxP-h-7CSPY,IbONvDW5DnM,okSJ_TNsQCA",
  "読んで！甘辛Script": "qLu7yyH50Ik",
  "誰より好きなのに": "tYxghZ_C5BE",
  "誰ソ彼アイデンティティー": "yoRFXVbMhSc,svWgm5ZvteY,sdsxf89-3DY",
  "谷の底で咲く花は": "iOHdA3wXs5A,wJAa6EkOeQ4",
  "贈る言葉": "v_sO7K9TXC0",
  "赤い世界が消える頃": "0MgtK30HFrM,FqRLcw7SzI0,jPE91YRV5k8",
  "赤い花咲いた": "",
  "赤裸々": "nnTdEpkOonQ",
  "走れ！": "_-XyrLc2iiU",
  "踊りまくろ☆ダンシング・ナイト": "piX4dzqoWq4",
  "躍るFLAGSHIP": "JsaMPcHTtzA",
  "躍るFLAGSHIP -ESTi Remix-": "1A5alFl4xTU",
  "輝きにかわる": "655IslBf05Y,gBAzYE_pvEg",
  "輝く世界の魔法": "McpkQXEypJk",
  "輝く世界の魔法 - しんげきRemix-": "Dlb6OCs0Sbs",
  "輝く世界の魔法 -Magical Step Forward Remix-": "Dlb6OCs0Sbs",
  "輝け！ビートシューター": "JYLgRtLJ_jg",
  "輝夜": "FqdhfULjN-o",
  "迅雷鉄火": "5mvt7_gLpt8,46IFe_HXoOs",
  "近道したい": "",
  "迷走Mind": "eaRQyTuhtdc",
  "追い風Running": "gW15pu80O6I,TmPibnf391k",
  "追憶のサンドグラス": "qJoryNOtcUA,g3SIc6VwaVU,CPMm6HHLNZQ",
  "追憶のサンドグラス (sky_delta Remix)": "1VQyXuSgxsE",
  "透明なプロローグ": "IHtKpiIq5VQ,5Wui7hYY26U,nTQ3xo0lmI8,Sjo0D8XKSJo,-ksPkGh7GYY",
  "透明なプロローグ (Snail's House Remix)": "Sjo0D8XKSJo",
  "週末だけのハーレクイン": "Xfx_aTjZj5o,_DdENUyVQ5o",
  "進路は超銀河": "E8Pyk6KyBao",
  "運命光年": "VfYcogV7aqo",
  "運命前夜": "jhMpX8qBzsE",
  "過純性ブリーチ": "u-_CHNNAOS4,sfGAMsCdoVg",
  "遠い街から": "",
  "遠い音楽": "",
  "遠く遠く": "",
  "部屋とYシャツと私": "fSbwqKUW1OY",
  "金の斧、銀の斧、エメラルドの斧": "YbyjjPC6wUQ,QmNvsC8SKcg",
  "鉄の羽のエクソダス": "A1rD5gmw9j4",
  "銀のイルカと熱い風": "DCDX4Rz-2nI,9pQPL_ZX1lQ",
  "銀のテーブル木苺ジャム": "KvXR9zMhYzk,XqsLuwqlkrY",
  "銀河図書館": "AEmfBH2qj70",
  "銀翼のアレジアンス -blade of truth-": "HcW46eyL2-0",
  "銀翼のアヴニール -become the brave-": "NDK9ryJVNiA",
  "隣に…": "1WXjtu5T6Ms",
  "離れていても": "whiipTsy5GU",
  "雨上がりのアイリス": "5GHsaG3gefo,cLygK7m6TwQ",
  "雪に願いを": "",
  "雪の華": "",
  "雪・月・風・花": "coX4G14ZHMI,mnkKbnWmJqg",
  "雪國": "",
  "雪解けに": "ZnUy-qYDhAo,zCkRjCVjmjk,qZQ4PphECHY",
  "電波感傷": "WVWqY8_LM0I,KwveVlij4lc",
  "青とオレンジ": "OEwHVuAhmjI",
  "青と夏": "y58_DLkpM14",
  "青の一番星": "02rfuOS-wj0,C2V_cz2bS8s",
  "青春のWanna!": "j1Y1mXpuobU,pVCh3EzFxSA,O4U7PZNrvMw",
  "青春コンプレックス": "RJMOrqaZ8hQ",
  "青春！サティスファクション": "Zehi_o4t9DI",
  "青空": "t2JqjztpEo4,qFyFJzjbs8s",
  "青空のナミダ": "",
  "青空エール": "k11RsQ0krQ0,4eGQ1hfdX5o",
  "青空リレーション": "stU33SK9vKE",
  "静かな夜に願いを…": "",
  "革命進化論": "5JkqSOrkLPc",
  "頂上決戦ヴィクトリー！！！！！！": "KGkdhAjWfSo,N3j8BR7VXUg",
  "風と雲と私": "",
  "風になりたい": "tkXQW_Mzoe0",
  "風の魔法": "",
  "風立ちぬ": "",
  "風色メロディ": "ST5NtayO8QU",
  "風色メロディ ～For Mio rearrange MIX～": "",
  "風花": "K_HzLzV-AoE",
  "飛べない僕は泳いだ": "04okvviUl58",
  "飛べない鳥は夜に鳴く": "gAArcjo_Km0",
  "飛べ！スカイキッド": "",
  "餞の鳥": "SkrDUncFvCk,U5lcuYppCcM,l1bNsUKKnqY",
  "高速道路": "",
  "高鳴る": "",
  "魂のルフラン": "",
  "魔法のステアー": "RTPNpdhgEpM",
  "魔法をかけて！": "NuwC9yukwuQ",
  "鳥の詩": "g_JcuRv8FYs",
  "鳥籠スクリプチュア": "od00D3_w2Mw,9STCCt5rxAw,pZHhCYtey74",
  "鳥籠スクリプチュア (5u5h1 Remix)": "cn7vKk21QkI",
  "黎明スターライン": "Oc6XCeSv8Xw,MEaWhx22sLY",
  "黒い犬": "",
  "＊ましゅまろ色のまほう使い＊": "ZOMH6_IIWG8",
  "１人ぼっちのうた": "",
};

async function main() {
  console.log('--- 開始更新歌曲 YouTube IDs ---');
  let updateCount = 0;

  const entries = Object.entries(youtubeIdsMap);
  const filledCount = entries.filter(([_, ids]) => ids.trim() !== '').length;
  console.log(`共有 ${entries.length} 首歌曲，其中 ${filledCount} 首已填寫 YouTube IDs，開始寫入資料庫...\n`);

  for (const [title, ids] of entries) {
    const youtubeIds = ids.trim() !== '' ? ids.trim() : null;

    if (!youtubeIds) {
      console.warn(`[跳過] 歌曲: 「${title}」 沒有提供 YouTube IDs。`);
      continue;
    }

    try {
      const result = await prisma.song.updateMany({
        where: {
          title: title,
        },
        data: {
          youtubeIds: youtubeIds,
        },
      });

      if (result.count > 0) {
        if (youtubeIds) {
          console.log(`[更新成功] 歌曲: 「${title}」 -> YouTube IDs: ${youtubeIds} (${result.count} 首)`);
        }
        updateCount += result.count;
      } else {
        console.warn(`[找不到歌曲] 資料庫中找不到曲名為 「${title}」 的歌曲。`);
      }
    } catch (error: any) {
      console.error(`[更新失敗] 歌曲: 「${title}」 寫入錯誤: ${error.message}`);
    }
  }

  console.log(`\n--- YouTube IDs 更新完畢！共更新了 ${updateCount} 筆記錄 ---`);
}

main()
  .catch((e) => {
    console.error('執行 Seed 腳本時發生錯誤:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
